
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Student: 'Student',
  Programme: 'Programme',
  StudentEnrollment: 'StudentEnrollment',
  PaymentTransaction: 'PaymentTransaction',
  Assessment: 'Assessment',
  AssessmentSubmission: 'AssessmentSubmission',
  UserLog: 'UserLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  passwordHash: 'passwordHash',
  role: 'role',
  isActive: 'isActive',
  studentId: 'studentId',
  isVerified: 'isVerified',
  otpHash: 'otpHash',
  otpExpiresAt: 'otpExpiresAt',
  otpAttempts: 'otpAttempts',
  otpSentAt: 'otpSentAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const StudentScalarFieldEnum = {
  id: 'id',
  studentUid: 'studentUid',
  fullName: 'fullName',
  email: 'email',
  dateOfBirth: 'dateOfBirth',
  academicYear: 'academicYear',
  status: 'status',
  hasOverdueBalance: 'hasOverdueBalance',
  userId: 'userId',
  programmeId: 'programmeId',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StudentScalarFieldEnum = (typeof StudentScalarFieldEnum)[keyof typeof StudentScalarFieldEnum]


export const ProgrammeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  fee: 'fee',
  discount: 'discount',
  coupon: 'coupon',
  couponLimit: 'couponLimit',
  couponUsed: 'couponUsed',
  status: 'status',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProgrammeScalarFieldEnum = (typeof ProgrammeScalarFieldEnum)[keyof typeof ProgrammeScalarFieldEnum]


export const StudentEnrollmentScalarFieldEnum = {
  id: 'id',
  reference: 'reference',
  studentId: 'studentId',
  programmeId: 'programmeId',
  enrolledYear: 'enrolledYear',
  status: 'status',
  feeSnapshot: 'feeSnapshot',
  discountSnapshot: 'discountSnapshot',
  feeTotal: 'feeTotal',
  dueDate: 'dueDate',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StudentEnrollmentScalarFieldEnum = (typeof StudentEnrollmentScalarFieldEnum)[keyof typeof StudentEnrollmentScalarFieldEnum]


export const PaymentTransactionScalarFieldEnum = {
  idempotencyKey: 'idempotencyKey',
  id: 'id',
  reference: 'reference',
  enrollmentId: 'enrollmentId',
  amount: 'amount',
  currency: 'currency',
  paymentDate: 'paymentDate',
  receivedById: 'receivedById',
  createdAt: 'createdAt',
  note: 'note'
} as const

export type PaymentTransactionScalarFieldEnum = (typeof PaymentTransactionScalarFieldEnum)[keyof typeof PaymentTransactionScalarFieldEnum]


export const AssessmentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subjectName: 'subjectName',
  moduleName: 'moduleName',
  programmeId: 'programmeId',
  createdById: 'createdById',
  dueDate: 'dueDate',
  extendedDeadline: 'extendedDeadline',
  maxMarks: 'maxMarks',
  totalMarks: 'totalMarks',
  highestGrade: 'highestGrade',
  resubmissionLimit: 'resubmissionLimit',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AssessmentScalarFieldEnum = (typeof AssessmentScalarFieldEnum)[keyof typeof AssessmentScalarFieldEnum]


export const AssessmentSubmissionScalarFieldEnum = {
  id: 'id',
  assessmentId: 'assessmentId',
  studentId: 'studentId',
  submittedAt: 'submittedAt',
  isLate: 'isLate',
  status: 'status',
  resubmissions: 'resubmissions',
  file_path: 'file_path',
  marks: 'marks',
  classification: 'classification',
  resultStatus: 'resultStatus',
  isPublished: 'isPublished',
  gradedById: 'gradedById',
  gradedAt: 'gradedAt',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AssessmentSubmissionScalarFieldEnum = (typeof AssessmentSubmissionScalarFieldEnum)[keyof typeof AssessmentSubmissionScalarFieldEnum]


export const UserLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  eventType: 'eventType',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type UserLogScalarFieldEnum = (typeof UserLogScalarFieldEnum)[keyof typeof UserLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

