
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Assessment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Assessment
 * Assessment ownership is programme-scoped. `subjectName` is intentionally
 * a scalar until the registry has a first-class module/course entity.
 */
export type AssessmentModel = runtime.Types.Result.DefaultSelection<Prisma.$AssessmentPayload>

export type AggregateAssessment = {
  _count: AssessmentCountAggregateOutputType | null
  _avg: AssessmentAvgAggregateOutputType | null
  _sum: AssessmentSumAggregateOutputType | null
  _min: AssessmentMinAggregateOutputType | null
  _max: AssessmentMaxAggregateOutputType | null
}

export type AssessmentAvgAggregateOutputType = {
  id: number | null
  programmeId: number | null
  createdById: number | null
  maxMarks: runtime.Decimal | null
  totalMarks: runtime.Decimal | null
  resubmissionLimit: number | null
  status: number | null
}

export type AssessmentSumAggregateOutputType = {
  id: number | null
  programmeId: number | null
  createdById: number | null
  maxMarks: runtime.Decimal | null
  totalMarks: runtime.Decimal | null
  resubmissionLimit: number | null
  status: number | null
}

export type AssessmentMinAggregateOutputType = {
  id: number | null
  title: string | null
  subjectName: string | null
  moduleName: string | null
  programmeId: number | null
  createdById: number | null
  dueDate: Date | null
  extendedDeadline: Date | null
  maxMarks: runtime.Decimal | null
  totalMarks: runtime.Decimal | null
  highestGrade: string | null
  resubmissionLimit: number | null
  status: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AssessmentMaxAggregateOutputType = {
  id: number | null
  title: string | null
  subjectName: string | null
  moduleName: string | null
  programmeId: number | null
  createdById: number | null
  dueDate: Date | null
  extendedDeadline: Date | null
  maxMarks: runtime.Decimal | null
  totalMarks: runtime.Decimal | null
  highestGrade: string | null
  resubmissionLimit: number | null
  status: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AssessmentCountAggregateOutputType = {
  id: number
  title: number
  subjectName: number
  moduleName: number
  programmeId: number
  createdById: number
  dueDate: number
  extendedDeadline: number
  maxMarks: number
  totalMarks: number
  highestGrade: number
  resubmissionLimit: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AssessmentAvgAggregateInputType = {
  id?: true
  programmeId?: true
  createdById?: true
  maxMarks?: true
  totalMarks?: true
  resubmissionLimit?: true
  status?: true
}

export type AssessmentSumAggregateInputType = {
  id?: true
  programmeId?: true
  createdById?: true
  maxMarks?: true
  totalMarks?: true
  resubmissionLimit?: true
  status?: true
}

export type AssessmentMinAggregateInputType = {
  id?: true
  title?: true
  subjectName?: true
  moduleName?: true
  programmeId?: true
  createdById?: true
  dueDate?: true
  extendedDeadline?: true
  maxMarks?: true
  totalMarks?: true
  highestGrade?: true
  resubmissionLimit?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type AssessmentMaxAggregateInputType = {
  id?: true
  title?: true
  subjectName?: true
  moduleName?: true
  programmeId?: true
  createdById?: true
  dueDate?: true
  extendedDeadline?: true
  maxMarks?: true
  totalMarks?: true
  highestGrade?: true
  resubmissionLimit?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type AssessmentCountAggregateInputType = {
  id?: true
  title?: true
  subjectName?: true
  moduleName?: true
  programmeId?: true
  createdById?: true
  dueDate?: true
  extendedDeadline?: true
  maxMarks?: true
  totalMarks?: true
  highestGrade?: true
  resubmissionLimit?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AssessmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assessment to aggregate.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Assessments
  **/
  _count?: true | AssessmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AssessmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AssessmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssessmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssessmentMaxAggregateInputType
}

export type GetAssessmentAggregateType<T extends AssessmentAggregateArgs> = {
      [P in keyof T & keyof AggregateAssessment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssessment[P]>
    : Prisma.GetScalarType<T[P], AggregateAssessment[P]>
}




export type AssessmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentWhereInput
  orderBy?: Prisma.AssessmentOrderByWithAggregationInput | Prisma.AssessmentOrderByWithAggregationInput[]
  by: Prisma.AssessmentScalarFieldEnum[] | Prisma.AssessmentScalarFieldEnum
  having?: Prisma.AssessmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssessmentCountAggregateInputType | true
  _avg?: AssessmentAvgAggregateInputType
  _sum?: AssessmentSumAggregateInputType
  _min?: AssessmentMinAggregateInputType
  _max?: AssessmentMaxAggregateInputType
}

export type AssessmentGroupByOutputType = {
  id: number
  title: string
  subjectName: string | null
  moduleName: string | null
  programmeId: number
  createdById: number
  dueDate: Date
  extendedDeadline: Date | null
  maxMarks: runtime.Decimal
  totalMarks: runtime.Decimal | null
  highestGrade: string | null
  resubmissionLimit: number
  status: number
  createdAt: Date
  updatedAt: Date
  _count: AssessmentCountAggregateOutputType | null
  _avg: AssessmentAvgAggregateOutputType | null
  _sum: AssessmentSumAggregateOutputType | null
  _min: AssessmentMinAggregateOutputType | null
  _max: AssessmentMaxAggregateOutputType | null
}

export type GetAssessmentGroupByPayload<T extends AssessmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssessmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssessmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssessmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssessmentGroupByOutputType[P]>
      }
    >
  >



export type AssessmentWhereInput = {
  AND?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  OR?: Prisma.AssessmentWhereInput[]
  NOT?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  id?: Prisma.IntFilter<"Assessment"> | number
  title?: Prisma.StringFilter<"Assessment"> | string
  subjectName?: Prisma.StringNullableFilter<"Assessment"> | string | null
  moduleName?: Prisma.StringNullableFilter<"Assessment"> | string | null
  programmeId?: Prisma.IntFilter<"Assessment"> | number
  createdById?: Prisma.IntFilter<"Assessment"> | number
  dueDate?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  extendedDeadline?: Prisma.DateTimeNullableFilter<"Assessment"> | Date | string | null
  maxMarks?: Prisma.DecimalFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.DecimalNullableFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.StringNullableFilter<"Assessment"> | string | null
  resubmissionLimit?: Prisma.IntFilter<"Assessment"> | number
  status?: Prisma.IntFilter<"Assessment"> | number
  createdAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  programme?: Prisma.XOR<Prisma.ProgrammeScalarRelationFilter, Prisma.ProgrammeWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  submissions?: Prisma.AssessmentSubmissionListRelationFilter
}

export type AssessmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subjectName?: Prisma.SortOrderInput | Prisma.SortOrder
  moduleName?: Prisma.SortOrderInput | Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  extendedDeadline?: Prisma.SortOrderInput | Prisma.SortOrder
  maxMarks?: Prisma.SortOrder
  totalMarks?: Prisma.SortOrderInput | Prisma.SortOrder
  highestGrade?: Prisma.SortOrderInput | Prisma.SortOrder
  resubmissionLimit?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  programme?: Prisma.ProgrammeOrderByWithRelationInput
  createdBy?: Prisma.UserOrderByWithRelationInput
  submissions?: Prisma.AssessmentSubmissionOrderByRelationAggregateInput
}

export type AssessmentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  OR?: Prisma.AssessmentWhereInput[]
  NOT?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  title?: Prisma.StringFilter<"Assessment"> | string
  subjectName?: Prisma.StringNullableFilter<"Assessment"> | string | null
  moduleName?: Prisma.StringNullableFilter<"Assessment"> | string | null
  programmeId?: Prisma.IntFilter<"Assessment"> | number
  createdById?: Prisma.IntFilter<"Assessment"> | number
  dueDate?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  extendedDeadline?: Prisma.DateTimeNullableFilter<"Assessment"> | Date | string | null
  maxMarks?: Prisma.DecimalFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.DecimalNullableFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.StringNullableFilter<"Assessment"> | string | null
  resubmissionLimit?: Prisma.IntFilter<"Assessment"> | number
  status?: Prisma.IntFilter<"Assessment"> | number
  createdAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  programme?: Prisma.XOR<Prisma.ProgrammeScalarRelationFilter, Prisma.ProgrammeWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  submissions?: Prisma.AssessmentSubmissionListRelationFilter
}, "id">

export type AssessmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subjectName?: Prisma.SortOrderInput | Prisma.SortOrder
  moduleName?: Prisma.SortOrderInput | Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  extendedDeadline?: Prisma.SortOrderInput | Prisma.SortOrder
  maxMarks?: Prisma.SortOrder
  totalMarks?: Prisma.SortOrderInput | Prisma.SortOrder
  highestGrade?: Prisma.SortOrderInput | Prisma.SortOrder
  resubmissionLimit?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AssessmentCountOrderByAggregateInput
  _avg?: Prisma.AssessmentAvgOrderByAggregateInput
  _max?: Prisma.AssessmentMaxOrderByAggregateInput
  _min?: Prisma.AssessmentMinOrderByAggregateInput
  _sum?: Prisma.AssessmentSumOrderByAggregateInput
}

export type AssessmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssessmentScalarWhereWithAggregatesInput | Prisma.AssessmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssessmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssessmentScalarWhereWithAggregatesInput | Prisma.AssessmentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Assessment"> | number
  title?: Prisma.StringWithAggregatesFilter<"Assessment"> | string
  subjectName?: Prisma.StringNullableWithAggregatesFilter<"Assessment"> | string | null
  moduleName?: Prisma.StringNullableWithAggregatesFilter<"Assessment"> | string | null
  programmeId?: Prisma.IntWithAggregatesFilter<"Assessment"> | number
  createdById?: Prisma.IntWithAggregatesFilter<"Assessment"> | number
  dueDate?: Prisma.DateTimeWithAggregatesFilter<"Assessment"> | Date | string
  extendedDeadline?: Prisma.DateTimeNullableWithAggregatesFilter<"Assessment"> | Date | string | null
  maxMarks?: Prisma.DecimalWithAggregatesFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.DecimalNullableWithAggregatesFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.StringNullableWithAggregatesFilter<"Assessment"> | string | null
  resubmissionLimit?: Prisma.IntWithAggregatesFilter<"Assessment"> | number
  status?: Prisma.IntWithAggregatesFilter<"Assessment"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Assessment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Assessment"> | Date | string
}

export type AssessmentCreateInput = {
  title: string
  subjectName?: string | null
  moduleName?: string | null
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  programme: Prisma.ProgrammeCreateNestedOneWithoutAssessmentsInput
  createdBy: Prisma.UserCreateNestedOneWithoutAssessmentsInput
  submissions?: Prisma.AssessmentSubmissionCreateNestedManyWithoutAssessmentInput
}

export type AssessmentUncheckedCreateInput = {
  id?: number
  title: string
  subjectName?: string | null
  moduleName?: string | null
  programmeId: number
  createdById: number
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedCreateNestedManyWithoutAssessmentInput
}

export type AssessmentUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  programme?: Prisma.ProgrammeUpdateOneRequiredWithoutAssessmentsNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutAssessmentsNestedInput
  submissions?: Prisma.AssessmentSubmissionUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  programmeId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentCreateManyInput = {
  id?: number
  title: string
  subjectName?: string | null
  moduleName?: string | null
  programmeId: number
  createdById: number
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssessmentUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  programmeId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentListRelationFilter = {
  every?: Prisma.AssessmentWhereInput
  some?: Prisma.AssessmentWhereInput
  none?: Prisma.AssessmentWhereInput
}

export type AssessmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssessmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subjectName?: Prisma.SortOrder
  moduleName?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  extendedDeadline?: Prisma.SortOrder
  maxMarks?: Prisma.SortOrder
  totalMarks?: Prisma.SortOrder
  highestGrade?: Prisma.SortOrder
  resubmissionLimit?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AssessmentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  maxMarks?: Prisma.SortOrder
  totalMarks?: Prisma.SortOrder
  resubmissionLimit?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type AssessmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subjectName?: Prisma.SortOrder
  moduleName?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  extendedDeadline?: Prisma.SortOrder
  maxMarks?: Prisma.SortOrder
  totalMarks?: Prisma.SortOrder
  highestGrade?: Prisma.SortOrder
  resubmissionLimit?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AssessmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subjectName?: Prisma.SortOrder
  moduleName?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  extendedDeadline?: Prisma.SortOrder
  maxMarks?: Prisma.SortOrder
  totalMarks?: Prisma.SortOrder
  highestGrade?: Prisma.SortOrder
  resubmissionLimit?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AssessmentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  maxMarks?: Prisma.SortOrder
  totalMarks?: Prisma.SortOrder
  resubmissionLimit?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type AssessmentScalarRelationFilter = {
  is?: Prisma.AssessmentWhereInput
  isNot?: Prisma.AssessmentWhereInput
}

export type AssessmentCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutCreatedByInput, Prisma.AssessmentUncheckedCreateWithoutCreatedByInput> | Prisma.AssessmentCreateWithoutCreatedByInput[] | Prisma.AssessmentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutCreatedByInput | Prisma.AssessmentCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.AssessmentCreateManyCreatedByInputEnvelope
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
}

export type AssessmentUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutCreatedByInput, Prisma.AssessmentUncheckedCreateWithoutCreatedByInput> | Prisma.AssessmentCreateWithoutCreatedByInput[] | Prisma.AssessmentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutCreatedByInput | Prisma.AssessmentCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.AssessmentCreateManyCreatedByInputEnvelope
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
}

export type AssessmentUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutCreatedByInput, Prisma.AssessmentUncheckedCreateWithoutCreatedByInput> | Prisma.AssessmentCreateWithoutCreatedByInput[] | Prisma.AssessmentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutCreatedByInput | Prisma.AssessmentCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.AssessmentUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.AssessmentUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.AssessmentCreateManyCreatedByInputEnvelope
  set?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  disconnect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  delete?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  update?: Prisma.AssessmentUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.AssessmentUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.AssessmentUpdateManyWithWhereWithoutCreatedByInput | Prisma.AssessmentUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
}

export type AssessmentUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutCreatedByInput, Prisma.AssessmentUncheckedCreateWithoutCreatedByInput> | Prisma.AssessmentCreateWithoutCreatedByInput[] | Prisma.AssessmentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutCreatedByInput | Prisma.AssessmentCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.AssessmentUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.AssessmentUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.AssessmentCreateManyCreatedByInputEnvelope
  set?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  disconnect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  delete?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  update?: Prisma.AssessmentUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.AssessmentUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.AssessmentUpdateManyWithWhereWithoutCreatedByInput | Prisma.AssessmentUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
}

export type AssessmentCreateNestedManyWithoutProgrammeInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutProgrammeInput, Prisma.AssessmentUncheckedCreateWithoutProgrammeInput> | Prisma.AssessmentCreateWithoutProgrammeInput[] | Prisma.AssessmentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutProgrammeInput | Prisma.AssessmentCreateOrConnectWithoutProgrammeInput[]
  createMany?: Prisma.AssessmentCreateManyProgrammeInputEnvelope
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
}

export type AssessmentUncheckedCreateNestedManyWithoutProgrammeInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutProgrammeInput, Prisma.AssessmentUncheckedCreateWithoutProgrammeInput> | Prisma.AssessmentCreateWithoutProgrammeInput[] | Prisma.AssessmentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutProgrammeInput | Prisma.AssessmentCreateOrConnectWithoutProgrammeInput[]
  createMany?: Prisma.AssessmentCreateManyProgrammeInputEnvelope
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
}

export type AssessmentUpdateManyWithoutProgrammeNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutProgrammeInput, Prisma.AssessmentUncheckedCreateWithoutProgrammeInput> | Prisma.AssessmentCreateWithoutProgrammeInput[] | Prisma.AssessmentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutProgrammeInput | Prisma.AssessmentCreateOrConnectWithoutProgrammeInput[]
  upsert?: Prisma.AssessmentUpsertWithWhereUniqueWithoutProgrammeInput | Prisma.AssessmentUpsertWithWhereUniqueWithoutProgrammeInput[]
  createMany?: Prisma.AssessmentCreateManyProgrammeInputEnvelope
  set?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  disconnect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  delete?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  update?: Prisma.AssessmentUpdateWithWhereUniqueWithoutProgrammeInput | Prisma.AssessmentUpdateWithWhereUniqueWithoutProgrammeInput[]
  updateMany?: Prisma.AssessmentUpdateManyWithWhereWithoutProgrammeInput | Prisma.AssessmentUpdateManyWithWhereWithoutProgrammeInput[]
  deleteMany?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
}

export type AssessmentUncheckedUpdateManyWithoutProgrammeNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutProgrammeInput, Prisma.AssessmentUncheckedCreateWithoutProgrammeInput> | Prisma.AssessmentCreateWithoutProgrammeInput[] | Prisma.AssessmentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutProgrammeInput | Prisma.AssessmentCreateOrConnectWithoutProgrammeInput[]
  upsert?: Prisma.AssessmentUpsertWithWhereUniqueWithoutProgrammeInput | Prisma.AssessmentUpsertWithWhereUniqueWithoutProgrammeInput[]
  createMany?: Prisma.AssessmentCreateManyProgrammeInputEnvelope
  set?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  disconnect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  delete?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  update?: Prisma.AssessmentUpdateWithWhereUniqueWithoutProgrammeInput | Prisma.AssessmentUpdateWithWhereUniqueWithoutProgrammeInput[]
  updateMany?: Prisma.AssessmentUpdateManyWithWhereWithoutProgrammeInput | Prisma.AssessmentUpdateManyWithWhereWithoutProgrammeInput[]
  deleteMany?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
}

export type AssessmentCreateNestedOneWithoutSubmissionsInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutSubmissionsInput, Prisma.AssessmentUncheckedCreateWithoutSubmissionsInput>
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutSubmissionsInput
  connect?: Prisma.AssessmentWhereUniqueInput
}

export type AssessmentUpdateOneRequiredWithoutSubmissionsNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutSubmissionsInput, Prisma.AssessmentUncheckedCreateWithoutSubmissionsInput>
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutSubmissionsInput
  upsert?: Prisma.AssessmentUpsertWithoutSubmissionsInput
  connect?: Prisma.AssessmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssessmentUpdateToOneWithWhereWithoutSubmissionsInput, Prisma.AssessmentUpdateWithoutSubmissionsInput>, Prisma.AssessmentUncheckedUpdateWithoutSubmissionsInput>
}

export type AssessmentCreateWithoutCreatedByInput = {
  title: string
  subjectName?: string | null
  moduleName?: string | null
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  programme: Prisma.ProgrammeCreateNestedOneWithoutAssessmentsInput
  submissions?: Prisma.AssessmentSubmissionCreateNestedManyWithoutAssessmentInput
}

export type AssessmentUncheckedCreateWithoutCreatedByInput = {
  id?: number
  title: string
  subjectName?: string | null
  moduleName?: string | null
  programmeId: number
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedCreateNestedManyWithoutAssessmentInput
}

export type AssessmentCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.AssessmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutCreatedByInput, Prisma.AssessmentUncheckedCreateWithoutCreatedByInput>
}

export type AssessmentCreateManyCreatedByInputEnvelope = {
  data: Prisma.AssessmentCreateManyCreatedByInput | Prisma.AssessmentCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type AssessmentUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.AssessmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AssessmentUpdateWithoutCreatedByInput, Prisma.AssessmentUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutCreatedByInput, Prisma.AssessmentUncheckedCreateWithoutCreatedByInput>
}

export type AssessmentUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.AssessmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AssessmentUpdateWithoutCreatedByInput, Prisma.AssessmentUncheckedUpdateWithoutCreatedByInput>
}

export type AssessmentUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.AssessmentScalarWhereInput
  data: Prisma.XOR<Prisma.AssessmentUpdateManyMutationInput, Prisma.AssessmentUncheckedUpdateManyWithoutCreatedByInput>
}

export type AssessmentScalarWhereInput = {
  AND?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
  OR?: Prisma.AssessmentScalarWhereInput[]
  NOT?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
  id?: Prisma.IntFilter<"Assessment"> | number
  title?: Prisma.StringFilter<"Assessment"> | string
  subjectName?: Prisma.StringNullableFilter<"Assessment"> | string | null
  moduleName?: Prisma.StringNullableFilter<"Assessment"> | string | null
  programmeId?: Prisma.IntFilter<"Assessment"> | number
  createdById?: Prisma.IntFilter<"Assessment"> | number
  dueDate?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  extendedDeadline?: Prisma.DateTimeNullableFilter<"Assessment"> | Date | string | null
  maxMarks?: Prisma.DecimalFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.DecimalNullableFilter<"Assessment"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.StringNullableFilter<"Assessment"> | string | null
  resubmissionLimit?: Prisma.IntFilter<"Assessment"> | number
  status?: Prisma.IntFilter<"Assessment"> | number
  createdAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
}

export type AssessmentCreateWithoutProgrammeInput = {
  title: string
  subjectName?: string | null
  moduleName?: string | null
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  createdBy: Prisma.UserCreateNestedOneWithoutAssessmentsInput
  submissions?: Prisma.AssessmentSubmissionCreateNestedManyWithoutAssessmentInput
}

export type AssessmentUncheckedCreateWithoutProgrammeInput = {
  id?: number
  title: string
  subjectName?: string | null
  moduleName?: string | null
  createdById: number
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedCreateNestedManyWithoutAssessmentInput
}

export type AssessmentCreateOrConnectWithoutProgrammeInput = {
  where: Prisma.AssessmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutProgrammeInput, Prisma.AssessmentUncheckedCreateWithoutProgrammeInput>
}

export type AssessmentCreateManyProgrammeInputEnvelope = {
  data: Prisma.AssessmentCreateManyProgrammeInput | Prisma.AssessmentCreateManyProgrammeInput[]
  skipDuplicates?: boolean
}

export type AssessmentUpsertWithWhereUniqueWithoutProgrammeInput = {
  where: Prisma.AssessmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AssessmentUpdateWithoutProgrammeInput, Prisma.AssessmentUncheckedUpdateWithoutProgrammeInput>
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutProgrammeInput, Prisma.AssessmentUncheckedCreateWithoutProgrammeInput>
}

export type AssessmentUpdateWithWhereUniqueWithoutProgrammeInput = {
  where: Prisma.AssessmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AssessmentUpdateWithoutProgrammeInput, Prisma.AssessmentUncheckedUpdateWithoutProgrammeInput>
}

export type AssessmentUpdateManyWithWhereWithoutProgrammeInput = {
  where: Prisma.AssessmentScalarWhereInput
  data: Prisma.XOR<Prisma.AssessmentUpdateManyMutationInput, Prisma.AssessmentUncheckedUpdateManyWithoutProgrammeInput>
}

export type AssessmentCreateWithoutSubmissionsInput = {
  title: string
  subjectName?: string | null
  moduleName?: string | null
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  programme: Prisma.ProgrammeCreateNestedOneWithoutAssessmentsInput
  createdBy: Prisma.UserCreateNestedOneWithoutAssessmentsInput
}

export type AssessmentUncheckedCreateWithoutSubmissionsInput = {
  id?: number
  title: string
  subjectName?: string | null
  moduleName?: string | null
  programmeId: number
  createdById: number
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssessmentCreateOrConnectWithoutSubmissionsInput = {
  where: Prisma.AssessmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutSubmissionsInput, Prisma.AssessmentUncheckedCreateWithoutSubmissionsInput>
}

export type AssessmentUpsertWithoutSubmissionsInput = {
  update: Prisma.XOR<Prisma.AssessmentUpdateWithoutSubmissionsInput, Prisma.AssessmentUncheckedUpdateWithoutSubmissionsInput>
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutSubmissionsInput, Prisma.AssessmentUncheckedCreateWithoutSubmissionsInput>
  where?: Prisma.AssessmentWhereInput
}

export type AssessmentUpdateToOneWithWhereWithoutSubmissionsInput = {
  where?: Prisma.AssessmentWhereInput
  data: Prisma.XOR<Prisma.AssessmentUpdateWithoutSubmissionsInput, Prisma.AssessmentUncheckedUpdateWithoutSubmissionsInput>
}

export type AssessmentUpdateWithoutSubmissionsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  programme?: Prisma.ProgrammeUpdateOneRequiredWithoutAssessmentsNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutAssessmentsNestedInput
}

export type AssessmentUncheckedUpdateWithoutSubmissionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  programmeId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentCreateManyCreatedByInput = {
  id?: number
  title: string
  subjectName?: string | null
  moduleName?: string | null
  programmeId: number
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssessmentUpdateWithoutCreatedByInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  programme?: Prisma.ProgrammeUpdateOneRequiredWithoutAssessmentsNestedInput
  submissions?: Prisma.AssessmentSubmissionUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  programmeId?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  programmeId?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentCreateManyProgrammeInput = {
  id?: number
  title: string
  subjectName?: string | null
  moduleName?: string | null
  createdById: number
  dueDate: Date | string
  extendedDeadline?: Date | string | null
  maxMarks: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: string | null
  resubmissionLimit?: number
  status?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AssessmentUpdateWithoutProgrammeInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneRequiredWithoutAssessmentsNestedInput
  submissions?: Prisma.AssessmentSubmissionUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateWithoutProgrammeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateManyWithoutProgrammeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subjectName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moduleName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extendedDeadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maxMarks?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalMarks?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  highestGrade?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resubmissionLimit?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AssessmentCountOutputType
 */

export type AssessmentCountOutputType = {
  submissions: number
}

export type AssessmentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submissions?: boolean | AssessmentCountOutputTypeCountSubmissionsArgs
}

/**
 * AssessmentCountOutputType without action
 */
export type AssessmentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentCountOutputType
   */
  select?: Prisma.AssessmentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AssessmentCountOutputType without action
 */
export type AssessmentCountOutputTypeCountSubmissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentSubmissionWhereInput
}


export type AssessmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  subjectName?: boolean
  moduleName?: boolean
  programmeId?: boolean
  createdById?: boolean
  dueDate?: boolean
  extendedDeadline?: boolean
  maxMarks?: boolean
  totalMarks?: boolean
  highestGrade?: boolean
  resubmissionLimit?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  programme?: boolean | Prisma.ProgrammeDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  submissions?: boolean | Prisma.Assessment$submissionsArgs<ExtArgs>
  _count?: boolean | Prisma.AssessmentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessment"]>

export type AssessmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  subjectName?: boolean
  moduleName?: boolean
  programmeId?: boolean
  createdById?: boolean
  dueDate?: boolean
  extendedDeadline?: boolean
  maxMarks?: boolean
  totalMarks?: boolean
  highestGrade?: boolean
  resubmissionLimit?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  programme?: boolean | Prisma.ProgrammeDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessment"]>

export type AssessmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  subjectName?: boolean
  moduleName?: boolean
  programmeId?: boolean
  createdById?: boolean
  dueDate?: boolean
  extendedDeadline?: boolean
  maxMarks?: boolean
  totalMarks?: boolean
  highestGrade?: boolean
  resubmissionLimit?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  programme?: boolean | Prisma.ProgrammeDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessment"]>

export type AssessmentSelectScalar = {
  id?: boolean
  title?: boolean
  subjectName?: boolean
  moduleName?: boolean
  programmeId?: boolean
  createdById?: boolean
  dueDate?: boolean
  extendedDeadline?: boolean
  maxMarks?: boolean
  totalMarks?: boolean
  highestGrade?: boolean
  resubmissionLimit?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AssessmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "subjectName" | "moduleName" | "programmeId" | "createdById" | "dueDate" | "extendedDeadline" | "maxMarks" | "totalMarks" | "highestGrade" | "resubmissionLimit" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["assessment"]>
export type AssessmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  programme?: boolean | Prisma.ProgrammeDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  submissions?: boolean | Prisma.Assessment$submissionsArgs<ExtArgs>
  _count?: boolean | Prisma.AssessmentCountOutputTypeDefaultArgs<ExtArgs>
}
export type AssessmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  programme?: boolean | Prisma.ProgrammeDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AssessmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  programme?: boolean | Prisma.ProgrammeDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AssessmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Assessment"
  objects: {
    programme: Prisma.$ProgrammePayload<ExtArgs>
    createdBy: Prisma.$UserPayload<ExtArgs>
    submissions: Prisma.$AssessmentSubmissionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    subjectName: string | null
    moduleName: string | null
    programmeId: number
    createdById: number
    dueDate: Date
    extendedDeadline: Date | null
    maxMarks: runtime.Decimal
    totalMarks: runtime.Decimal | null
    highestGrade: string | null
    resubmissionLimit: number
    status: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["assessment"]>
  composites: {}
}

export type AssessmentGetPayload<S extends boolean | null | undefined | AssessmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssessmentPayload, S>

export type AssessmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssessmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssessmentCountAggregateInputType | true
  }

export interface AssessmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Assessment'], meta: { name: 'Assessment' } }
  /**
   * Find zero or one Assessment that matches the filter.
   * @param {AssessmentFindUniqueArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssessmentFindUniqueArgs>(args: Prisma.SelectSubset<T, AssessmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Assessment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssessmentFindUniqueOrThrowArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssessmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssessmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Assessment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentFindFirstArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssessmentFindFirstArgs>(args?: Prisma.SelectSubset<T, AssessmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Assessment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentFindFirstOrThrowArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssessmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssessmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Assessments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Assessments
   * const assessments = await prisma.assessment.findMany()
   * 
   * // Get first 10 Assessments
   * const assessments = await prisma.assessment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assessmentWithIdOnly = await prisma.assessment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssessmentFindManyArgs>(args?: Prisma.SelectSubset<T, AssessmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Assessment.
   * @param {AssessmentCreateArgs} args - Arguments to create a Assessment.
   * @example
   * // Create one Assessment
   * const Assessment = await prisma.assessment.create({
   *   data: {
   *     // ... data to create a Assessment
   *   }
   * })
   * 
   */
  create<T extends AssessmentCreateArgs>(args: Prisma.SelectSubset<T, AssessmentCreateArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Assessments.
   * @param {AssessmentCreateManyArgs} args - Arguments to create many Assessments.
   * @example
   * // Create many Assessments
   * const assessment = await prisma.assessment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssessmentCreateManyArgs>(args?: Prisma.SelectSubset<T, AssessmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Assessments and returns the data saved in the database.
   * @param {AssessmentCreateManyAndReturnArgs} args - Arguments to create many Assessments.
   * @example
   * // Create many Assessments
   * const assessment = await prisma.assessment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Assessments and only return the `id`
   * const assessmentWithIdOnly = await prisma.assessment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssessmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssessmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Assessment.
   * @param {AssessmentDeleteArgs} args - Arguments to delete one Assessment.
   * @example
   * // Delete one Assessment
   * const Assessment = await prisma.assessment.delete({
   *   where: {
   *     // ... filter to delete one Assessment
   *   }
   * })
   * 
   */
  delete<T extends AssessmentDeleteArgs>(args: Prisma.SelectSubset<T, AssessmentDeleteArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Assessment.
   * @param {AssessmentUpdateArgs} args - Arguments to update one Assessment.
   * @example
   * // Update one Assessment
   * const assessment = await prisma.assessment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssessmentUpdateArgs>(args: Prisma.SelectSubset<T, AssessmentUpdateArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Assessments.
   * @param {AssessmentDeleteManyArgs} args - Arguments to filter Assessments to delete.
   * @example
   * // Delete a few Assessments
   * const { count } = await prisma.assessment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssessmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssessmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assessments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Assessments
   * const assessment = await prisma.assessment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssessmentUpdateManyArgs>(args: Prisma.SelectSubset<T, AssessmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assessments and returns the data updated in the database.
   * @param {AssessmentUpdateManyAndReturnArgs} args - Arguments to update many Assessments.
   * @example
   * // Update many Assessments
   * const assessment = await prisma.assessment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Assessments and only return the `id`
   * const assessmentWithIdOnly = await prisma.assessment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssessmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssessmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Assessment.
   * @param {AssessmentUpsertArgs} args - Arguments to update or create a Assessment.
   * @example
   * // Update or create a Assessment
   * const assessment = await prisma.assessment.upsert({
   *   create: {
   *     // ... data to create a Assessment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Assessment we want to update
   *   }
   * })
   */
  upsert<T extends AssessmentUpsertArgs>(args: Prisma.SelectSubset<T, AssessmentUpsertArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Assessments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentCountArgs} args - Arguments to filter Assessments to count.
   * @example
   * // Count the number of Assessments
   * const count = await prisma.assessment.count({
   *   where: {
   *     // ... the filter for the Assessments we want to count
   *   }
   * })
  **/
  count<T extends AssessmentCountArgs>(
    args?: Prisma.Subset<T, AssessmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssessmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Assessment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssessmentAggregateArgs>(args: Prisma.Subset<T, AssessmentAggregateArgs>): Prisma.PrismaPromise<GetAssessmentAggregateType<T>>

  /**
   * Group by Assessment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssessmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssessmentGroupByArgs['orderBy'] }
      : { orderBy?: AssessmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssessmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssessmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Assessment model
 */
readonly fields: AssessmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Assessment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssessmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  programme<T extends Prisma.ProgrammeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProgrammeDefaultArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  createdBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  submissions<T extends Prisma.Assessment$submissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Assessment$submissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentSubmissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Assessment model
 */
export interface AssessmentFieldRefs {
  readonly id: Prisma.FieldRef<"Assessment", 'Int'>
  readonly title: Prisma.FieldRef<"Assessment", 'String'>
  readonly subjectName: Prisma.FieldRef<"Assessment", 'String'>
  readonly moduleName: Prisma.FieldRef<"Assessment", 'String'>
  readonly programmeId: Prisma.FieldRef<"Assessment", 'Int'>
  readonly createdById: Prisma.FieldRef<"Assessment", 'Int'>
  readonly dueDate: Prisma.FieldRef<"Assessment", 'DateTime'>
  readonly extendedDeadline: Prisma.FieldRef<"Assessment", 'DateTime'>
  readonly maxMarks: Prisma.FieldRef<"Assessment", 'Decimal'>
  readonly totalMarks: Prisma.FieldRef<"Assessment", 'Decimal'>
  readonly highestGrade: Prisma.FieldRef<"Assessment", 'String'>
  readonly resubmissionLimit: Prisma.FieldRef<"Assessment", 'Int'>
  readonly status: Prisma.FieldRef<"Assessment", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Assessment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Assessment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Assessment findUnique
 */
export type AssessmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment findUniqueOrThrow
 */
export type AssessmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment findFirst
 */
export type AssessmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assessments.
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assessments.
   */
  distinct?: Prisma.AssessmentScalarFieldEnum | Prisma.AssessmentScalarFieldEnum[]
}

/**
 * Assessment findFirstOrThrow
 */
export type AssessmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assessments.
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assessments.
   */
  distinct?: Prisma.AssessmentScalarFieldEnum | Prisma.AssessmentScalarFieldEnum[]
}

/**
 * Assessment findMany
 */
export type AssessmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessments to fetch.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Assessments.
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assessments.
   */
  distinct?: Prisma.AssessmentScalarFieldEnum | Prisma.AssessmentScalarFieldEnum[]
}

/**
 * Assessment create
 */
export type AssessmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * The data needed to create a Assessment.
   */
  data: Prisma.XOR<Prisma.AssessmentCreateInput, Prisma.AssessmentUncheckedCreateInput>
}

/**
 * Assessment createMany
 */
export type AssessmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Assessments.
   */
  data: Prisma.AssessmentCreateManyInput | Prisma.AssessmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Assessment createManyAndReturn
 */
export type AssessmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * The data used to create many Assessments.
   */
  data: Prisma.AssessmentCreateManyInput | Prisma.AssessmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Assessment update
 */
export type AssessmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * The data needed to update a Assessment.
   */
  data: Prisma.XOR<Prisma.AssessmentUpdateInput, Prisma.AssessmentUncheckedUpdateInput>
  /**
   * Choose, which Assessment to update.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment updateMany
 */
export type AssessmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Assessments.
   */
  data: Prisma.XOR<Prisma.AssessmentUpdateManyMutationInput, Prisma.AssessmentUncheckedUpdateManyInput>
  /**
   * Filter which Assessments to update
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * Limit how many Assessments to update.
   */
  limit?: number
}

/**
 * Assessment updateManyAndReturn
 */
export type AssessmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * The data used to update Assessments.
   */
  data: Prisma.XOR<Prisma.AssessmentUpdateManyMutationInput, Prisma.AssessmentUncheckedUpdateManyInput>
  /**
   * Filter which Assessments to update
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * Limit how many Assessments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Assessment upsert
 */
export type AssessmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * The filter to search for the Assessment to update in case it exists.
   */
  where: Prisma.AssessmentWhereUniqueInput
  /**
   * In case the Assessment found by the `where` argument doesn't exist, create a new Assessment with this data.
   */
  create: Prisma.XOR<Prisma.AssessmentCreateInput, Prisma.AssessmentUncheckedCreateInput>
  /**
   * In case the Assessment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssessmentUpdateInput, Prisma.AssessmentUncheckedUpdateInput>
}

/**
 * Assessment delete
 */
export type AssessmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter which Assessment to delete.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment deleteMany
 */
export type AssessmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assessments to delete
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * Limit how many Assessments to delete.
   */
  limit?: number
}

/**
 * Assessment.submissions
 */
export type Assessment$submissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentSubmission
   */
  select?: Prisma.AssessmentSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentSubmission
   */
  omit?: Prisma.AssessmentSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentSubmissionInclude<ExtArgs> | null
  where?: Prisma.AssessmentSubmissionWhereInput
  orderBy?: Prisma.AssessmentSubmissionOrderByWithRelationInput | Prisma.AssessmentSubmissionOrderByWithRelationInput[]
  cursor?: Prisma.AssessmentSubmissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssessmentSubmissionScalarFieldEnum | Prisma.AssessmentSubmissionScalarFieldEnum[]
}

/**
 * Assessment without action
 */
export type AssessmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
}
