
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Programme` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Programme
 * Catalogue data only. Enrolment and payment workflows are separate features.
 */
export type ProgrammeModel = runtime.Types.Result.DefaultSelection<Prisma.$ProgrammePayload>

export type AggregateProgramme = {
  _count: ProgrammeCountAggregateOutputType | null
  _avg: ProgrammeAvgAggregateOutputType | null
  _sum: ProgrammeSumAggregateOutputType | null
  _min: ProgrammeMinAggregateOutputType | null
  _max: ProgrammeMaxAggregateOutputType | null
}

export type ProgrammeAvgAggregateOutputType = {
  id: number | null
  fee: runtime.Decimal | null
  discount: runtime.Decimal | null
  couponLimit: number | null
  couponUsed: number | null
}

export type ProgrammeSumAggregateOutputType = {
  id: number | null
  fee: runtime.Decimal | null
  discount: runtime.Decimal | null
  couponLimit: number | null
  couponUsed: number | null
}

export type ProgrammeMinAggregateOutputType = {
  id: number | null
  name: string | null
  fee: runtime.Decimal | null
  discount: runtime.Decimal | null
  coupon: string | null
  couponLimit: number | null
  couponUsed: number | null
  status: $Enums.ProgrammeStatus | null
  deletedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProgrammeMaxAggregateOutputType = {
  id: number | null
  name: string | null
  fee: runtime.Decimal | null
  discount: runtime.Decimal | null
  coupon: string | null
  couponLimit: number | null
  couponUsed: number | null
  status: $Enums.ProgrammeStatus | null
  deletedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProgrammeCountAggregateOutputType = {
  id: number
  name: number
  fee: number
  discount: number
  coupon: number
  couponLimit: number
  couponUsed: number
  status: number
  deletedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProgrammeAvgAggregateInputType = {
  id?: true
  fee?: true
  discount?: true
  couponLimit?: true
  couponUsed?: true
}

export type ProgrammeSumAggregateInputType = {
  id?: true
  fee?: true
  discount?: true
  couponLimit?: true
  couponUsed?: true
}

export type ProgrammeMinAggregateInputType = {
  id?: true
  name?: true
  fee?: true
  discount?: true
  coupon?: true
  couponLimit?: true
  couponUsed?: true
  status?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type ProgrammeMaxAggregateInputType = {
  id?: true
  name?: true
  fee?: true
  discount?: true
  coupon?: true
  couponLimit?: true
  couponUsed?: true
  status?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type ProgrammeCountAggregateInputType = {
  id?: true
  name?: true
  fee?: true
  discount?: true
  coupon?: true
  couponLimit?: true
  couponUsed?: true
  status?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProgrammeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Programme to aggregate.
   */
  where?: Prisma.ProgrammeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Programmes to fetch.
   */
  orderBy?: Prisma.ProgrammeOrderByWithRelationInput | Prisma.ProgrammeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProgrammeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Programmes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Programmes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Programmes
  **/
  _count?: true | ProgrammeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProgrammeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProgrammeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProgrammeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProgrammeMaxAggregateInputType
}

export type GetProgrammeAggregateType<T extends ProgrammeAggregateArgs> = {
      [P in keyof T & keyof AggregateProgramme]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProgramme[P]>
    : Prisma.GetScalarType<T[P], AggregateProgramme[P]>
}




export type ProgrammeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProgrammeWhereInput
  orderBy?: Prisma.ProgrammeOrderByWithAggregationInput | Prisma.ProgrammeOrderByWithAggregationInput[]
  by: Prisma.ProgrammeScalarFieldEnum[] | Prisma.ProgrammeScalarFieldEnum
  having?: Prisma.ProgrammeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProgrammeCountAggregateInputType | true
  _avg?: ProgrammeAvgAggregateInputType
  _sum?: ProgrammeSumAggregateInputType
  _min?: ProgrammeMinAggregateInputType
  _max?: ProgrammeMaxAggregateInputType
}

export type ProgrammeGroupByOutputType = {
  id: number
  name: string
  fee: runtime.Decimal
  discount: runtime.Decimal
  coupon: string | null
  couponLimit: number | null
  couponUsed: number
  status: $Enums.ProgrammeStatus
  deletedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: ProgrammeCountAggregateOutputType | null
  _avg: ProgrammeAvgAggregateOutputType | null
  _sum: ProgrammeSumAggregateOutputType | null
  _min: ProgrammeMinAggregateOutputType | null
  _max: ProgrammeMaxAggregateOutputType | null
}

export type GetProgrammeGroupByPayload<T extends ProgrammeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProgrammeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProgrammeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProgrammeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProgrammeGroupByOutputType[P]>
      }
    >
  >



export type ProgrammeWhereInput = {
  AND?: Prisma.ProgrammeWhereInput | Prisma.ProgrammeWhereInput[]
  OR?: Prisma.ProgrammeWhereInput[]
  NOT?: Prisma.ProgrammeWhereInput | Prisma.ProgrammeWhereInput[]
  id?: Prisma.IntFilter<"Programme"> | number
  name?: Prisma.StringFilter<"Programme"> | string
  fee?: Prisma.DecimalFilter<"Programme"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"Programme"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.StringNullableFilter<"Programme"> | string | null
  couponLimit?: Prisma.IntNullableFilter<"Programme"> | number | null
  couponUsed?: Prisma.IntFilter<"Programme"> | number
  status?: Prisma.EnumProgrammeStatusFilter<"Programme"> | $Enums.ProgrammeStatus
  deletedAt?: Prisma.DateTimeNullableFilter<"Programme"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Programme"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Programme"> | Date | string
  students?: Prisma.StudentListRelationFilter
  enrollments?: Prisma.StudentEnrollmentListRelationFilter
  assessments?: Prisma.AssessmentListRelationFilter
}

export type ProgrammeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  coupon?: Prisma.SortOrderInput | Prisma.SortOrder
  couponLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  couponUsed?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  students?: Prisma.StudentOrderByRelationAggregateInput
  enrollments?: Prisma.StudentEnrollmentOrderByRelationAggregateInput
  assessments?: Prisma.AssessmentOrderByRelationAggregateInput
}

export type ProgrammeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  AND?: Prisma.ProgrammeWhereInput | Prisma.ProgrammeWhereInput[]
  OR?: Prisma.ProgrammeWhereInput[]
  NOT?: Prisma.ProgrammeWhereInput | Prisma.ProgrammeWhereInput[]
  fee?: Prisma.DecimalFilter<"Programme"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"Programme"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.StringNullableFilter<"Programme"> | string | null
  couponLimit?: Prisma.IntNullableFilter<"Programme"> | number | null
  couponUsed?: Prisma.IntFilter<"Programme"> | number
  status?: Prisma.EnumProgrammeStatusFilter<"Programme"> | $Enums.ProgrammeStatus
  deletedAt?: Prisma.DateTimeNullableFilter<"Programme"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Programme"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Programme"> | Date | string
  students?: Prisma.StudentListRelationFilter
  enrollments?: Prisma.StudentEnrollmentListRelationFilter
  assessments?: Prisma.AssessmentListRelationFilter
}, "id" | "name">

export type ProgrammeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  coupon?: Prisma.SortOrderInput | Prisma.SortOrder
  couponLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  couponUsed?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProgrammeCountOrderByAggregateInput
  _avg?: Prisma.ProgrammeAvgOrderByAggregateInput
  _max?: Prisma.ProgrammeMaxOrderByAggregateInput
  _min?: Prisma.ProgrammeMinOrderByAggregateInput
  _sum?: Prisma.ProgrammeSumOrderByAggregateInput
}

export type ProgrammeScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProgrammeScalarWhereWithAggregatesInput | Prisma.ProgrammeScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProgrammeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProgrammeScalarWhereWithAggregatesInput | Prisma.ProgrammeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Programme"> | number
  name?: Prisma.StringWithAggregatesFilter<"Programme"> | string
  fee?: Prisma.DecimalWithAggregatesFilter<"Programme"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalWithAggregatesFilter<"Programme"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.StringNullableWithAggregatesFilter<"Programme"> | string | null
  couponLimit?: Prisma.IntNullableWithAggregatesFilter<"Programme"> | number | null
  couponUsed?: Prisma.IntWithAggregatesFilter<"Programme"> | number
  status?: Prisma.EnumProgrammeStatusWithAggregatesFilter<"Programme"> | $Enums.ProgrammeStatus
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Programme"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Programme"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Programme"> | Date | string
}

export type ProgrammeCreateInput = {
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  students?: Prisma.StudentCreateNestedManyWithoutProgrammeInput
  enrollments?: Prisma.StudentEnrollmentCreateNestedManyWithoutProgrammeInput
  assessments?: Prisma.AssessmentCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeUncheckedCreateInput = {
  id?: number
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  students?: Prisma.StudentUncheckedCreateNestedManyWithoutProgrammeInput
  enrollments?: Prisma.StudentEnrollmentUncheckedCreateNestedManyWithoutProgrammeInput
  assessments?: Prisma.AssessmentUncheckedCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  students?: Prisma.StudentUpdateManyWithoutProgrammeNestedInput
  enrollments?: Prisma.StudentEnrollmentUpdateManyWithoutProgrammeNestedInput
  assessments?: Prisma.AssessmentUpdateManyWithoutProgrammeNestedInput
}

export type ProgrammeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  students?: Prisma.StudentUncheckedUpdateManyWithoutProgrammeNestedInput
  enrollments?: Prisma.StudentEnrollmentUncheckedUpdateManyWithoutProgrammeNestedInput
  assessments?: Prisma.AssessmentUncheckedUpdateManyWithoutProgrammeNestedInput
}

export type ProgrammeCreateManyInput = {
  id?: number
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProgrammeUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProgrammeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProgrammeNullableScalarRelationFilter = {
  is?: Prisma.ProgrammeWhereInput | null
  isNot?: Prisma.ProgrammeWhereInput | null
}

export type ProgrammeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  coupon?: Prisma.SortOrder
  couponLimit?: Prisma.SortOrder
  couponUsed?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProgrammeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  couponLimit?: Prisma.SortOrder
  couponUsed?: Prisma.SortOrder
}

export type ProgrammeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  coupon?: Prisma.SortOrder
  couponLimit?: Prisma.SortOrder
  couponUsed?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProgrammeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  coupon?: Prisma.SortOrder
  couponLimit?: Prisma.SortOrder
  couponUsed?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProgrammeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  couponLimit?: Prisma.SortOrder
  couponUsed?: Prisma.SortOrder
}

export type ProgrammeScalarRelationFilter = {
  is?: Prisma.ProgrammeWhereInput
  isNot?: Prisma.ProgrammeWhereInput
}

export type ProgrammeCreateNestedOneWithoutStudentsInput = {
  create?: Prisma.XOR<Prisma.ProgrammeCreateWithoutStudentsInput, Prisma.ProgrammeUncheckedCreateWithoutStudentsInput>
  connectOrCreate?: Prisma.ProgrammeCreateOrConnectWithoutStudentsInput
  connect?: Prisma.ProgrammeWhereUniqueInput
}

export type ProgrammeUpdateOneWithoutStudentsNestedInput = {
  create?: Prisma.XOR<Prisma.ProgrammeCreateWithoutStudentsInput, Prisma.ProgrammeUncheckedCreateWithoutStudentsInput>
  connectOrCreate?: Prisma.ProgrammeCreateOrConnectWithoutStudentsInput
  upsert?: Prisma.ProgrammeUpsertWithoutStudentsInput
  disconnect?: Prisma.ProgrammeWhereInput | boolean
  delete?: Prisma.ProgrammeWhereInput | boolean
  connect?: Prisma.ProgrammeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProgrammeUpdateToOneWithWhereWithoutStudentsInput, Prisma.ProgrammeUpdateWithoutStudentsInput>, Prisma.ProgrammeUncheckedUpdateWithoutStudentsInput>
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type EnumProgrammeStatusFieldUpdateOperationsInput = {
  set?: $Enums.ProgrammeStatus
}

export type ProgrammeCreateNestedOneWithoutEnrollmentsInput = {
  create?: Prisma.XOR<Prisma.ProgrammeCreateWithoutEnrollmentsInput, Prisma.ProgrammeUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.ProgrammeCreateOrConnectWithoutEnrollmentsInput
  connect?: Prisma.ProgrammeWhereUniqueInput
}

export type ProgrammeUpdateOneRequiredWithoutEnrollmentsNestedInput = {
  create?: Prisma.XOR<Prisma.ProgrammeCreateWithoutEnrollmentsInput, Prisma.ProgrammeUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.ProgrammeCreateOrConnectWithoutEnrollmentsInput
  upsert?: Prisma.ProgrammeUpsertWithoutEnrollmentsInput
  connect?: Prisma.ProgrammeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProgrammeUpdateToOneWithWhereWithoutEnrollmentsInput, Prisma.ProgrammeUpdateWithoutEnrollmentsInput>, Prisma.ProgrammeUncheckedUpdateWithoutEnrollmentsInput>
}

export type ProgrammeCreateNestedOneWithoutAssessmentsInput = {
  create?: Prisma.XOR<Prisma.ProgrammeCreateWithoutAssessmentsInput, Prisma.ProgrammeUncheckedCreateWithoutAssessmentsInput>
  connectOrCreate?: Prisma.ProgrammeCreateOrConnectWithoutAssessmentsInput
  connect?: Prisma.ProgrammeWhereUniqueInput
}

export type ProgrammeUpdateOneRequiredWithoutAssessmentsNestedInput = {
  create?: Prisma.XOR<Prisma.ProgrammeCreateWithoutAssessmentsInput, Prisma.ProgrammeUncheckedCreateWithoutAssessmentsInput>
  connectOrCreate?: Prisma.ProgrammeCreateOrConnectWithoutAssessmentsInput
  upsert?: Prisma.ProgrammeUpsertWithoutAssessmentsInput
  connect?: Prisma.ProgrammeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProgrammeUpdateToOneWithWhereWithoutAssessmentsInput, Prisma.ProgrammeUpdateWithoutAssessmentsInput>, Prisma.ProgrammeUncheckedUpdateWithoutAssessmentsInput>
}

export type ProgrammeCreateWithoutStudentsInput = {
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.StudentEnrollmentCreateNestedManyWithoutProgrammeInput
  assessments?: Prisma.AssessmentCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeUncheckedCreateWithoutStudentsInput = {
  id?: number
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedCreateNestedManyWithoutProgrammeInput
  assessments?: Prisma.AssessmentUncheckedCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeCreateOrConnectWithoutStudentsInput = {
  where: Prisma.ProgrammeWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgrammeCreateWithoutStudentsInput, Prisma.ProgrammeUncheckedCreateWithoutStudentsInput>
}

export type ProgrammeUpsertWithoutStudentsInput = {
  update: Prisma.XOR<Prisma.ProgrammeUpdateWithoutStudentsInput, Prisma.ProgrammeUncheckedUpdateWithoutStudentsInput>
  create: Prisma.XOR<Prisma.ProgrammeCreateWithoutStudentsInput, Prisma.ProgrammeUncheckedCreateWithoutStudentsInput>
  where?: Prisma.ProgrammeWhereInput
}

export type ProgrammeUpdateToOneWithWhereWithoutStudentsInput = {
  where?: Prisma.ProgrammeWhereInput
  data: Prisma.XOR<Prisma.ProgrammeUpdateWithoutStudentsInput, Prisma.ProgrammeUncheckedUpdateWithoutStudentsInput>
}

export type ProgrammeUpdateWithoutStudentsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.StudentEnrollmentUpdateManyWithoutProgrammeNestedInput
  assessments?: Prisma.AssessmentUpdateManyWithoutProgrammeNestedInput
}

export type ProgrammeUncheckedUpdateWithoutStudentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedUpdateManyWithoutProgrammeNestedInput
  assessments?: Prisma.AssessmentUncheckedUpdateManyWithoutProgrammeNestedInput
}

export type ProgrammeCreateWithoutEnrollmentsInput = {
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  students?: Prisma.StudentCreateNestedManyWithoutProgrammeInput
  assessments?: Prisma.AssessmentCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeUncheckedCreateWithoutEnrollmentsInput = {
  id?: number
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  students?: Prisma.StudentUncheckedCreateNestedManyWithoutProgrammeInput
  assessments?: Prisma.AssessmentUncheckedCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeCreateOrConnectWithoutEnrollmentsInput = {
  where: Prisma.ProgrammeWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgrammeCreateWithoutEnrollmentsInput, Prisma.ProgrammeUncheckedCreateWithoutEnrollmentsInput>
}

export type ProgrammeUpsertWithoutEnrollmentsInput = {
  update: Prisma.XOR<Prisma.ProgrammeUpdateWithoutEnrollmentsInput, Prisma.ProgrammeUncheckedUpdateWithoutEnrollmentsInput>
  create: Prisma.XOR<Prisma.ProgrammeCreateWithoutEnrollmentsInput, Prisma.ProgrammeUncheckedCreateWithoutEnrollmentsInput>
  where?: Prisma.ProgrammeWhereInput
}

export type ProgrammeUpdateToOneWithWhereWithoutEnrollmentsInput = {
  where?: Prisma.ProgrammeWhereInput
  data: Prisma.XOR<Prisma.ProgrammeUpdateWithoutEnrollmentsInput, Prisma.ProgrammeUncheckedUpdateWithoutEnrollmentsInput>
}

export type ProgrammeUpdateWithoutEnrollmentsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  students?: Prisma.StudentUpdateManyWithoutProgrammeNestedInput
  assessments?: Prisma.AssessmentUpdateManyWithoutProgrammeNestedInput
}

export type ProgrammeUncheckedUpdateWithoutEnrollmentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  students?: Prisma.StudentUncheckedUpdateManyWithoutProgrammeNestedInput
  assessments?: Prisma.AssessmentUncheckedUpdateManyWithoutProgrammeNestedInput
}

export type ProgrammeCreateWithoutAssessmentsInput = {
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  students?: Prisma.StudentCreateNestedManyWithoutProgrammeInput
  enrollments?: Prisma.StudentEnrollmentCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeUncheckedCreateWithoutAssessmentsInput = {
  id?: number
  name: string
  fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: string | null
  couponLimit?: number | null
  couponUsed?: number
  status?: $Enums.ProgrammeStatus
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  students?: Prisma.StudentUncheckedCreateNestedManyWithoutProgrammeInput
  enrollments?: Prisma.StudentEnrollmentUncheckedCreateNestedManyWithoutProgrammeInput
}

export type ProgrammeCreateOrConnectWithoutAssessmentsInput = {
  where: Prisma.ProgrammeWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgrammeCreateWithoutAssessmentsInput, Prisma.ProgrammeUncheckedCreateWithoutAssessmentsInput>
}

export type ProgrammeUpsertWithoutAssessmentsInput = {
  update: Prisma.XOR<Prisma.ProgrammeUpdateWithoutAssessmentsInput, Prisma.ProgrammeUncheckedUpdateWithoutAssessmentsInput>
  create: Prisma.XOR<Prisma.ProgrammeCreateWithoutAssessmentsInput, Prisma.ProgrammeUncheckedCreateWithoutAssessmentsInput>
  where?: Prisma.ProgrammeWhereInput
}

export type ProgrammeUpdateToOneWithWhereWithoutAssessmentsInput = {
  where?: Prisma.ProgrammeWhereInput
  data: Prisma.XOR<Prisma.ProgrammeUpdateWithoutAssessmentsInput, Prisma.ProgrammeUncheckedUpdateWithoutAssessmentsInput>
}

export type ProgrammeUpdateWithoutAssessmentsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  students?: Prisma.StudentUpdateManyWithoutProgrammeNestedInput
  enrollments?: Prisma.StudentEnrollmentUpdateManyWithoutProgrammeNestedInput
}

export type ProgrammeUncheckedUpdateWithoutAssessmentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  coupon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  couponLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  couponUsed?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumProgrammeStatusFieldUpdateOperationsInput | $Enums.ProgrammeStatus
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  students?: Prisma.StudentUncheckedUpdateManyWithoutProgrammeNestedInput
  enrollments?: Prisma.StudentEnrollmentUncheckedUpdateManyWithoutProgrammeNestedInput
}


/**
 * Count Type ProgrammeCountOutputType
 */

export type ProgrammeCountOutputType = {
  students: number
  enrollments: number
  assessments: number
}

export type ProgrammeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  students?: boolean | ProgrammeCountOutputTypeCountStudentsArgs
  enrollments?: boolean | ProgrammeCountOutputTypeCountEnrollmentsArgs
  assessments?: boolean | ProgrammeCountOutputTypeCountAssessmentsArgs
}

/**
 * ProgrammeCountOutputType without action
 */
export type ProgrammeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgrammeCountOutputType
   */
  select?: Prisma.ProgrammeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProgrammeCountOutputType without action
 */
export type ProgrammeCountOutputTypeCountStudentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentWhereInput
}

/**
 * ProgrammeCountOutputType without action
 */
export type ProgrammeCountOutputTypeCountEnrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentEnrollmentWhereInput
}

/**
 * ProgrammeCountOutputType without action
 */
export type ProgrammeCountOutputTypeCountAssessmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentWhereInput
}


export type ProgrammeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  fee?: boolean
  discount?: boolean
  coupon?: boolean
  couponLimit?: boolean
  couponUsed?: boolean
  status?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  students?: boolean | Prisma.Programme$studentsArgs<ExtArgs>
  enrollments?: boolean | Prisma.Programme$enrollmentsArgs<ExtArgs>
  assessments?: boolean | Prisma.Programme$assessmentsArgs<ExtArgs>
  _count?: boolean | Prisma.ProgrammeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["programme"]>

export type ProgrammeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  fee?: boolean
  discount?: boolean
  coupon?: boolean
  couponLimit?: boolean
  couponUsed?: boolean
  status?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["programme"]>

export type ProgrammeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  fee?: boolean
  discount?: boolean
  coupon?: boolean
  couponLimit?: boolean
  couponUsed?: boolean
  status?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["programme"]>

export type ProgrammeSelectScalar = {
  id?: boolean
  name?: boolean
  fee?: boolean
  discount?: boolean
  coupon?: boolean
  couponLimit?: boolean
  couponUsed?: boolean
  status?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProgrammeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "fee" | "discount" | "coupon" | "couponLimit" | "couponUsed" | "status" | "deletedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["programme"]>
export type ProgrammeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  students?: boolean | Prisma.Programme$studentsArgs<ExtArgs>
  enrollments?: boolean | Prisma.Programme$enrollmentsArgs<ExtArgs>
  assessments?: boolean | Prisma.Programme$assessmentsArgs<ExtArgs>
  _count?: boolean | Prisma.ProgrammeCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProgrammeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProgrammeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProgrammePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Programme"
  objects: {
    students: Prisma.$StudentPayload<ExtArgs>[]
    enrollments: Prisma.$StudentEnrollmentPayload<ExtArgs>[]
    assessments: Prisma.$AssessmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    fee: runtime.Decimal
    discount: runtime.Decimal
    coupon: string | null
    couponLimit: number | null
    couponUsed: number
    status: $Enums.ProgrammeStatus
    deletedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["programme"]>
  composites: {}
}

export type ProgrammeGetPayload<S extends boolean | null | undefined | ProgrammeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProgrammePayload, S>

export type ProgrammeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProgrammeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProgrammeCountAggregateInputType | true
  }

export interface ProgrammeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Programme'], meta: { name: 'Programme' } }
  /**
   * Find zero or one Programme that matches the filter.
   * @param {ProgrammeFindUniqueArgs} args - Arguments to find a Programme
   * @example
   * // Get one Programme
   * const programme = await prisma.programme.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProgrammeFindUniqueArgs>(args: Prisma.SelectSubset<T, ProgrammeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Programme that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProgrammeFindUniqueOrThrowArgs} args - Arguments to find a Programme
   * @example
   * // Get one Programme
   * const programme = await prisma.programme.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProgrammeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProgrammeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Programme that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgrammeFindFirstArgs} args - Arguments to find a Programme
   * @example
   * // Get one Programme
   * const programme = await prisma.programme.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProgrammeFindFirstArgs>(args?: Prisma.SelectSubset<T, ProgrammeFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Programme that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgrammeFindFirstOrThrowArgs} args - Arguments to find a Programme
   * @example
   * // Get one Programme
   * const programme = await prisma.programme.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProgrammeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProgrammeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Programmes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgrammeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Programmes
   * const programmes = await prisma.programme.findMany()
   * 
   * // Get first 10 Programmes
   * const programmes = await prisma.programme.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const programmeWithIdOnly = await prisma.programme.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProgrammeFindManyArgs>(args?: Prisma.SelectSubset<T, ProgrammeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Programme.
   * @param {ProgrammeCreateArgs} args - Arguments to create a Programme.
   * @example
   * // Create one Programme
   * const Programme = await prisma.programme.create({
   *   data: {
   *     // ... data to create a Programme
   *   }
   * })
   * 
   */
  create<T extends ProgrammeCreateArgs>(args: Prisma.SelectSubset<T, ProgrammeCreateArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Programmes.
   * @param {ProgrammeCreateManyArgs} args - Arguments to create many Programmes.
   * @example
   * // Create many Programmes
   * const programme = await prisma.programme.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProgrammeCreateManyArgs>(args?: Prisma.SelectSubset<T, ProgrammeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Programmes and returns the data saved in the database.
   * @param {ProgrammeCreateManyAndReturnArgs} args - Arguments to create many Programmes.
   * @example
   * // Create many Programmes
   * const programme = await prisma.programme.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Programmes and only return the `id`
   * const programmeWithIdOnly = await prisma.programme.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProgrammeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProgrammeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Programme.
   * @param {ProgrammeDeleteArgs} args - Arguments to delete one Programme.
   * @example
   * // Delete one Programme
   * const Programme = await prisma.programme.delete({
   *   where: {
   *     // ... filter to delete one Programme
   *   }
   * })
   * 
   */
  delete<T extends ProgrammeDeleteArgs>(args: Prisma.SelectSubset<T, ProgrammeDeleteArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Programme.
   * @param {ProgrammeUpdateArgs} args - Arguments to update one Programme.
   * @example
   * // Update one Programme
   * const programme = await prisma.programme.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProgrammeUpdateArgs>(args: Prisma.SelectSubset<T, ProgrammeUpdateArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Programmes.
   * @param {ProgrammeDeleteManyArgs} args - Arguments to filter Programmes to delete.
   * @example
   * // Delete a few Programmes
   * const { count } = await prisma.programme.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProgrammeDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProgrammeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Programmes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgrammeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Programmes
   * const programme = await prisma.programme.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProgrammeUpdateManyArgs>(args: Prisma.SelectSubset<T, ProgrammeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Programmes and returns the data updated in the database.
   * @param {ProgrammeUpdateManyAndReturnArgs} args - Arguments to update many Programmes.
   * @example
   * // Update many Programmes
   * const programme = await prisma.programme.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Programmes and only return the `id`
   * const programmeWithIdOnly = await prisma.programme.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProgrammeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProgrammeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Programme.
   * @param {ProgrammeUpsertArgs} args - Arguments to update or create a Programme.
   * @example
   * // Update or create a Programme
   * const programme = await prisma.programme.upsert({
   *   create: {
   *     // ... data to create a Programme
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Programme we want to update
   *   }
   * })
   */
  upsert<T extends ProgrammeUpsertArgs>(args: Prisma.SelectSubset<T, ProgrammeUpsertArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Programmes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgrammeCountArgs} args - Arguments to filter Programmes to count.
   * @example
   * // Count the number of Programmes
   * const count = await prisma.programme.count({
   *   where: {
   *     // ... the filter for the Programmes we want to count
   *   }
   * })
  **/
  count<T extends ProgrammeCountArgs>(
    args?: Prisma.Subset<T, ProgrammeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProgrammeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Programme.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgrammeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProgrammeAggregateArgs>(args: Prisma.Subset<T, ProgrammeAggregateArgs>): Prisma.PrismaPromise<GetProgrammeAggregateType<T>>

  /**
   * Group by Programme.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgrammeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProgrammeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProgrammeGroupByArgs['orderBy'] }
      : { orderBy?: ProgrammeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProgrammeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProgrammeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Programme model
 */
readonly fields: ProgrammeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Programme.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProgrammeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  students<T extends Prisma.Programme$studentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Programme$studentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  enrollments<T extends Prisma.Programme$enrollmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Programme$enrollmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentEnrollmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  assessments<T extends Prisma.Programme$assessmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Programme$assessmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Programme model
 */
export interface ProgrammeFieldRefs {
  readonly id: Prisma.FieldRef<"Programme", 'Int'>
  readonly name: Prisma.FieldRef<"Programme", 'String'>
  readonly fee: Prisma.FieldRef<"Programme", 'Decimal'>
  readonly discount: Prisma.FieldRef<"Programme", 'Decimal'>
  readonly coupon: Prisma.FieldRef<"Programme", 'String'>
  readonly couponLimit: Prisma.FieldRef<"Programme", 'Int'>
  readonly couponUsed: Prisma.FieldRef<"Programme", 'Int'>
  readonly status: Prisma.FieldRef<"Programme", 'ProgrammeStatus'>
  readonly deletedAt: Prisma.FieldRef<"Programme", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Programme", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Programme", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Programme findUnique
 */
export type ProgrammeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * Filter, which Programme to fetch.
   */
  where: Prisma.ProgrammeWhereUniqueInput
}

/**
 * Programme findUniqueOrThrow
 */
export type ProgrammeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * Filter, which Programme to fetch.
   */
  where: Prisma.ProgrammeWhereUniqueInput
}

/**
 * Programme findFirst
 */
export type ProgrammeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * Filter, which Programme to fetch.
   */
  where?: Prisma.ProgrammeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Programmes to fetch.
   */
  orderBy?: Prisma.ProgrammeOrderByWithRelationInput | Prisma.ProgrammeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Programmes.
   */
  cursor?: Prisma.ProgrammeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Programmes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Programmes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Programmes.
   */
  distinct?: Prisma.ProgrammeScalarFieldEnum | Prisma.ProgrammeScalarFieldEnum[]
}

/**
 * Programme findFirstOrThrow
 */
export type ProgrammeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * Filter, which Programme to fetch.
   */
  where?: Prisma.ProgrammeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Programmes to fetch.
   */
  orderBy?: Prisma.ProgrammeOrderByWithRelationInput | Prisma.ProgrammeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Programmes.
   */
  cursor?: Prisma.ProgrammeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Programmes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Programmes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Programmes.
   */
  distinct?: Prisma.ProgrammeScalarFieldEnum | Prisma.ProgrammeScalarFieldEnum[]
}

/**
 * Programme findMany
 */
export type ProgrammeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * Filter, which Programmes to fetch.
   */
  where?: Prisma.ProgrammeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Programmes to fetch.
   */
  orderBy?: Prisma.ProgrammeOrderByWithRelationInput | Prisma.ProgrammeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Programmes.
   */
  cursor?: Prisma.ProgrammeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Programmes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Programmes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Programmes.
   */
  distinct?: Prisma.ProgrammeScalarFieldEnum | Prisma.ProgrammeScalarFieldEnum[]
}

/**
 * Programme create
 */
export type ProgrammeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * The data needed to create a Programme.
   */
  data: Prisma.XOR<Prisma.ProgrammeCreateInput, Prisma.ProgrammeUncheckedCreateInput>
}

/**
 * Programme createMany
 */
export type ProgrammeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Programmes.
   */
  data: Prisma.ProgrammeCreateManyInput | Prisma.ProgrammeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Programme createManyAndReturn
 */
export type ProgrammeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * The data used to create many Programmes.
   */
  data: Prisma.ProgrammeCreateManyInput | Prisma.ProgrammeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Programme update
 */
export type ProgrammeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * The data needed to update a Programme.
   */
  data: Prisma.XOR<Prisma.ProgrammeUpdateInput, Prisma.ProgrammeUncheckedUpdateInput>
  /**
   * Choose, which Programme to update.
   */
  where: Prisma.ProgrammeWhereUniqueInput
}

/**
 * Programme updateMany
 */
export type ProgrammeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Programmes.
   */
  data: Prisma.XOR<Prisma.ProgrammeUpdateManyMutationInput, Prisma.ProgrammeUncheckedUpdateManyInput>
  /**
   * Filter which Programmes to update
   */
  where?: Prisma.ProgrammeWhereInput
  /**
   * Limit how many Programmes to update.
   */
  limit?: number
}

/**
 * Programme updateManyAndReturn
 */
export type ProgrammeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * The data used to update Programmes.
   */
  data: Prisma.XOR<Prisma.ProgrammeUpdateManyMutationInput, Prisma.ProgrammeUncheckedUpdateManyInput>
  /**
   * Filter which Programmes to update
   */
  where?: Prisma.ProgrammeWhereInput
  /**
   * Limit how many Programmes to update.
   */
  limit?: number
}

/**
 * Programme upsert
 */
export type ProgrammeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * The filter to search for the Programme to update in case it exists.
   */
  where: Prisma.ProgrammeWhereUniqueInput
  /**
   * In case the Programme found by the `where` argument doesn't exist, create a new Programme with this data.
   */
  create: Prisma.XOR<Prisma.ProgrammeCreateInput, Prisma.ProgrammeUncheckedCreateInput>
  /**
   * In case the Programme was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProgrammeUpdateInput, Prisma.ProgrammeUncheckedUpdateInput>
}

/**
 * Programme delete
 */
export type ProgrammeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  /**
   * Filter which Programme to delete.
   */
  where: Prisma.ProgrammeWhereUniqueInput
}

/**
 * Programme deleteMany
 */
export type ProgrammeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Programmes to delete
   */
  where?: Prisma.ProgrammeWhereInput
  /**
   * Limit how many Programmes to delete.
   */
  limit?: number
}

/**
 * Programme.students
 */
export type Programme$studentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  where?: Prisma.StudentWhereInput
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  cursor?: Prisma.StudentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudentScalarFieldEnum | Prisma.StudentScalarFieldEnum[]
}

/**
 * Programme.enrollments
 */
export type Programme$enrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentEnrollment
   */
  select?: Prisma.StudentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentEnrollment
   */
  omit?: Prisma.StudentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentEnrollmentInclude<ExtArgs> | null
  where?: Prisma.StudentEnrollmentWhereInput
  orderBy?: Prisma.StudentEnrollmentOrderByWithRelationInput | Prisma.StudentEnrollmentOrderByWithRelationInput[]
  cursor?: Prisma.StudentEnrollmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudentEnrollmentScalarFieldEnum | Prisma.StudentEnrollmentScalarFieldEnum[]
}

/**
 * Programme.assessments
 */
export type Programme$assessmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  where?: Prisma.AssessmentWhereInput
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  cursor?: Prisma.AssessmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssessmentScalarFieldEnum | Prisma.AssessmentScalarFieldEnum[]
}

/**
 * Programme without action
 */
export type ProgrammeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
}
