
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Student` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Student
 * Registry record for a student. Authentication remains owned by User.
 * Student-facing identity is `studentUid`; retain the legacy User link while
 * registry routes still use it.
 */
export type StudentModel = runtime.Types.Result.DefaultSelection<Prisma.$StudentPayload>

export type AggregateStudent = {
  _count: StudentCountAggregateOutputType | null
  _avg: StudentAvgAggregateOutputType | null
  _sum: StudentSumAggregateOutputType | null
  _min: StudentMinAggregateOutputType | null
  _max: StudentMaxAggregateOutputType | null
}

export type StudentAvgAggregateOutputType = {
  id: number | null
  academicYear: number | null
  status: number | null
  userId: number | null
  programmeId: number | null
}

export type StudentSumAggregateOutputType = {
  id: number | null
  academicYear: number | null
  status: number | null
  userId: number | null
  programmeId: number | null
}

export type StudentMinAggregateOutputType = {
  id: number | null
  studentUid: string | null
  fullName: string | null
  email: string | null
  dateOfBirth: Date | null
  academicYear: number | null
  status: number | null
  hasOverdueBalance: boolean | null
  userId: number | null
  programmeId: number | null
  deletedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StudentMaxAggregateOutputType = {
  id: number | null
  studentUid: string | null
  fullName: string | null
  email: string | null
  dateOfBirth: Date | null
  academicYear: number | null
  status: number | null
  hasOverdueBalance: boolean | null
  userId: number | null
  programmeId: number | null
  deletedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StudentCountAggregateOutputType = {
  id: number
  studentUid: number
  fullName: number
  email: number
  dateOfBirth: number
  academicYear: number
  status: number
  hasOverdueBalance: number
  userId: number
  programmeId: number
  deletedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StudentAvgAggregateInputType = {
  id?: true
  academicYear?: true
  status?: true
  userId?: true
  programmeId?: true
}

export type StudentSumAggregateInputType = {
  id?: true
  academicYear?: true
  status?: true
  userId?: true
  programmeId?: true
}

export type StudentMinAggregateInputType = {
  id?: true
  studentUid?: true
  fullName?: true
  email?: true
  dateOfBirth?: true
  academicYear?: true
  status?: true
  hasOverdueBalance?: true
  userId?: true
  programmeId?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type StudentMaxAggregateInputType = {
  id?: true
  studentUid?: true
  fullName?: true
  email?: true
  dateOfBirth?: true
  academicYear?: true
  status?: true
  hasOverdueBalance?: true
  userId?: true
  programmeId?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type StudentCountAggregateInputType = {
  id?: true
  studentUid?: true
  fullName?: true
  email?: true
  dateOfBirth?: true
  academicYear?: true
  status?: true
  hasOverdueBalance?: true
  userId?: true
  programmeId?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StudentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Student to aggregate.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Students
  **/
  _count?: true | StudentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StudentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StudentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StudentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StudentMaxAggregateInputType
}

export type GetStudentAggregateType<T extends StudentAggregateArgs> = {
      [P in keyof T & keyof AggregateStudent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudent[P]>
    : Prisma.GetScalarType<T[P], AggregateStudent[P]>
}




export type StudentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentWhereInput
  orderBy?: Prisma.StudentOrderByWithAggregationInput | Prisma.StudentOrderByWithAggregationInput[]
  by: Prisma.StudentScalarFieldEnum[] | Prisma.StudentScalarFieldEnum
  having?: Prisma.StudentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StudentCountAggregateInputType | true
  _avg?: StudentAvgAggregateInputType
  _sum?: StudentSumAggregateInputType
  _min?: StudentMinAggregateInputType
  _max?: StudentMaxAggregateInputType
}

export type StudentGroupByOutputType = {
  id: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth: Date | null
  academicYear: number | null
  status: number
  hasOverdueBalance: boolean
  userId: number | null
  programmeId: number | null
  deletedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: StudentCountAggregateOutputType | null
  _avg: StudentAvgAggregateOutputType | null
  _sum: StudentSumAggregateOutputType | null
  _min: StudentMinAggregateOutputType | null
  _max: StudentMaxAggregateOutputType | null
}

export type GetStudentGroupByPayload<T extends StudentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StudentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StudentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StudentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StudentGroupByOutputType[P]>
      }
    >
  >



export type StudentWhereInput = {
  AND?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  OR?: Prisma.StudentWhereInput[]
  NOT?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  id?: Prisma.IntFilter<"Student"> | number
  studentUid?: Prisma.StringFilter<"Student"> | string
  fullName?: Prisma.StringFilter<"Student"> | string
  email?: Prisma.StringFilter<"Student"> | string
  dateOfBirth?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  academicYear?: Prisma.IntNullableFilter<"Student"> | number | null
  status?: Prisma.IntFilter<"Student"> | number
  hasOverdueBalance?: Prisma.BoolFilter<"Student"> | boolean
  userId?: Prisma.IntNullableFilter<"Student"> | number | null
  programmeId?: Prisma.IntNullableFilter<"Student"> | number | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  programme?: Prisma.XOR<Prisma.ProgrammeNullableScalarRelationFilter, Prisma.ProgrammeWhereInput> | null
  enrollments?: Prisma.StudentEnrollmentListRelationFilter
  submissions?: Prisma.AssessmentSubmissionListRelationFilter
}

export type StudentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  studentUid?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrderInput | Prisma.SortOrder
  academicYear?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  hasOverdueBalance?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  programmeId?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  programme?: Prisma.ProgrammeOrderByWithRelationInput
  enrollments?: Prisma.StudentEnrollmentOrderByRelationAggregateInput
  submissions?: Prisma.AssessmentSubmissionOrderByRelationAggregateInput
}

export type StudentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  studentUid?: string
  email?: string
  userId?: number
  AND?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  OR?: Prisma.StudentWhereInput[]
  NOT?: Prisma.StudentWhereInput | Prisma.StudentWhereInput[]
  fullName?: Prisma.StringFilter<"Student"> | string
  dateOfBirth?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  academicYear?: Prisma.IntNullableFilter<"Student"> | number | null
  status?: Prisma.IntFilter<"Student"> | number
  hasOverdueBalance?: Prisma.BoolFilter<"Student"> | boolean
  programmeId?: Prisma.IntNullableFilter<"Student"> | number | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  programme?: Prisma.XOR<Prisma.ProgrammeNullableScalarRelationFilter, Prisma.ProgrammeWhereInput> | null
  enrollments?: Prisma.StudentEnrollmentListRelationFilter
  submissions?: Prisma.AssessmentSubmissionListRelationFilter
}, "id" | "studentUid" | "email" | "userId">

export type StudentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  studentUid?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrderInput | Prisma.SortOrder
  academicYear?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  hasOverdueBalance?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  programmeId?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StudentCountOrderByAggregateInput
  _avg?: Prisma.StudentAvgOrderByAggregateInput
  _max?: Prisma.StudentMaxOrderByAggregateInput
  _min?: Prisma.StudentMinOrderByAggregateInput
  _sum?: Prisma.StudentSumOrderByAggregateInput
}

export type StudentScalarWhereWithAggregatesInput = {
  AND?: Prisma.StudentScalarWhereWithAggregatesInput | Prisma.StudentScalarWhereWithAggregatesInput[]
  OR?: Prisma.StudentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StudentScalarWhereWithAggregatesInput | Prisma.StudentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Student"> | number
  studentUid?: Prisma.StringWithAggregatesFilter<"Student"> | string
  fullName?: Prisma.StringWithAggregatesFilter<"Student"> | string
  email?: Prisma.StringWithAggregatesFilter<"Student"> | string
  dateOfBirth?: Prisma.DateTimeNullableWithAggregatesFilter<"Student"> | Date | string | null
  academicYear?: Prisma.IntNullableWithAggregatesFilter<"Student"> | number | null
  status?: Prisma.IntWithAggregatesFilter<"Student"> | number
  hasOverdueBalance?: Prisma.BoolWithAggregatesFilter<"Student"> | boolean
  userId?: Prisma.IntNullableWithAggregatesFilter<"Student"> | number | null
  programmeId?: Prisma.IntNullableWithAggregatesFilter<"Student"> | number | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Student"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Student"> | Date | string
}

export type StudentCreateInput = {
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutStudentInput
  programme?: Prisma.ProgrammeCreateNestedOneWithoutStudentsInput
  enrollments?: Prisma.StudentEnrollmentCreateNestedManyWithoutStudentInput
  submissions?: Prisma.AssessmentSubmissionCreateNestedManyWithoutStudentInput
}

export type StudentUncheckedCreateInput = {
  id?: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  userId?: number | null
  programmeId?: number | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedCreateNestedManyWithoutStudentInput
  submissions?: Prisma.AssessmentSubmissionUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentUpdateInput = {
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutStudentNestedInput
  programme?: Prisma.ProgrammeUpdateOneWithoutStudentsNestedInput
  enrollments?: Prisma.StudentEnrollmentUpdateManyWithoutStudentNestedInput
  submissions?: Prisma.AssessmentSubmissionUpdateManyWithoutStudentNestedInput
}

export type StudentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  programmeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedUpdateManyWithoutStudentNestedInput
  submissions?: Prisma.AssessmentSubmissionUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentCreateManyInput = {
  id?: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  userId?: number | null
  programmeId?: number | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StudentUpdateManyMutationInput = {
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StudentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  programmeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StudentNullableScalarRelationFilter = {
  is?: Prisma.StudentWhereInput | null
  isNot?: Prisma.StudentWhereInput | null
}

export type StudentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentUid?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hasOverdueBalance?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StudentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
}

export type StudentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentUid?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hasOverdueBalance?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StudentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentUid?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hasOverdueBalance?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StudentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  programmeId?: Prisma.SortOrder
}

export type StudentListRelationFilter = {
  every?: Prisma.StudentWhereInput
  some?: Prisma.StudentWhereInput
  none?: Prisma.StudentWhereInput
}

export type StudentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StudentScalarRelationFilter = {
  is?: Prisma.StudentWhereInput
  isNot?: Prisma.StudentWhereInput
}

export type StudentCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutUserInput, Prisma.StudentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutUserInput
  connect?: Prisma.StudentWhereUniqueInput
}

export type StudentUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutUserInput, Prisma.StudentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutUserInput
  connect?: Prisma.StudentWhereUniqueInput
}

export type StudentUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutUserInput, Prisma.StudentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutUserInput
  upsert?: Prisma.StudentUpsertWithoutUserInput
  disconnect?: Prisma.StudentWhereInput | boolean
  delete?: Prisma.StudentWhereInput | boolean
  connect?: Prisma.StudentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentUpdateToOneWithWhereWithoutUserInput, Prisma.StudentUpdateWithoutUserInput>, Prisma.StudentUncheckedUpdateWithoutUserInput>
}

export type StudentUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutUserInput, Prisma.StudentUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutUserInput
  upsert?: Prisma.StudentUpsertWithoutUserInput
  disconnect?: Prisma.StudentWhereInput | boolean
  delete?: Prisma.StudentWhereInput | boolean
  connect?: Prisma.StudentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentUpdateToOneWithWhereWithoutUserInput, Prisma.StudentUpdateWithoutUserInput>, Prisma.StudentUncheckedUpdateWithoutUserInput>
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type StudentCreateNestedManyWithoutProgrammeInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutProgrammeInput, Prisma.StudentUncheckedCreateWithoutProgrammeInput> | Prisma.StudentCreateWithoutProgrammeInput[] | Prisma.StudentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutProgrammeInput | Prisma.StudentCreateOrConnectWithoutProgrammeInput[]
  createMany?: Prisma.StudentCreateManyProgrammeInputEnvelope
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentUncheckedCreateNestedManyWithoutProgrammeInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutProgrammeInput, Prisma.StudentUncheckedCreateWithoutProgrammeInput> | Prisma.StudentCreateWithoutProgrammeInput[] | Prisma.StudentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutProgrammeInput | Prisma.StudentCreateOrConnectWithoutProgrammeInput[]
  createMany?: Prisma.StudentCreateManyProgrammeInputEnvelope
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
}

export type StudentUpdateManyWithoutProgrammeNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutProgrammeInput, Prisma.StudentUncheckedCreateWithoutProgrammeInput> | Prisma.StudentCreateWithoutProgrammeInput[] | Prisma.StudentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutProgrammeInput | Prisma.StudentCreateOrConnectWithoutProgrammeInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutProgrammeInput | Prisma.StudentUpsertWithWhereUniqueWithoutProgrammeInput[]
  createMany?: Prisma.StudentCreateManyProgrammeInputEnvelope
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutProgrammeInput | Prisma.StudentUpdateWithWhereUniqueWithoutProgrammeInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutProgrammeInput | Prisma.StudentUpdateManyWithWhereWithoutProgrammeInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentUncheckedUpdateManyWithoutProgrammeNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutProgrammeInput, Prisma.StudentUncheckedCreateWithoutProgrammeInput> | Prisma.StudentCreateWithoutProgrammeInput[] | Prisma.StudentUncheckedCreateWithoutProgrammeInput[]
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutProgrammeInput | Prisma.StudentCreateOrConnectWithoutProgrammeInput[]
  upsert?: Prisma.StudentUpsertWithWhereUniqueWithoutProgrammeInput | Prisma.StudentUpsertWithWhereUniqueWithoutProgrammeInput[]
  createMany?: Prisma.StudentCreateManyProgrammeInputEnvelope
  set?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  disconnect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  delete?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  connect?: Prisma.StudentWhereUniqueInput | Prisma.StudentWhereUniqueInput[]
  update?: Prisma.StudentUpdateWithWhereUniqueWithoutProgrammeInput | Prisma.StudentUpdateWithWhereUniqueWithoutProgrammeInput[]
  updateMany?: Prisma.StudentUpdateManyWithWhereWithoutProgrammeInput | Prisma.StudentUpdateManyWithWhereWithoutProgrammeInput[]
  deleteMany?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
}

export type StudentCreateNestedOneWithoutEnrollmentsInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutEnrollmentsInput, Prisma.StudentUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutEnrollmentsInput
  connect?: Prisma.StudentWhereUniqueInput
}

export type StudentUpdateOneRequiredWithoutEnrollmentsNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutEnrollmentsInput, Prisma.StudentUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutEnrollmentsInput
  upsert?: Prisma.StudentUpsertWithoutEnrollmentsInput
  connect?: Prisma.StudentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentUpdateToOneWithWhereWithoutEnrollmentsInput, Prisma.StudentUpdateWithoutEnrollmentsInput>, Prisma.StudentUncheckedUpdateWithoutEnrollmentsInput>
}

export type StudentCreateNestedOneWithoutSubmissionsInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutSubmissionsInput, Prisma.StudentUncheckedCreateWithoutSubmissionsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutSubmissionsInput
  connect?: Prisma.StudentWhereUniqueInput
}

export type StudentUpdateOneRequiredWithoutSubmissionsNestedInput = {
  create?: Prisma.XOR<Prisma.StudentCreateWithoutSubmissionsInput, Prisma.StudentUncheckedCreateWithoutSubmissionsInput>
  connectOrCreate?: Prisma.StudentCreateOrConnectWithoutSubmissionsInput
  upsert?: Prisma.StudentUpsertWithoutSubmissionsInput
  connect?: Prisma.StudentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentUpdateToOneWithWhereWithoutSubmissionsInput, Prisma.StudentUpdateWithoutSubmissionsInput>, Prisma.StudentUncheckedUpdateWithoutSubmissionsInput>
}

export type StudentCreateWithoutUserInput = {
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  programme?: Prisma.ProgrammeCreateNestedOneWithoutStudentsInput
  enrollments?: Prisma.StudentEnrollmentCreateNestedManyWithoutStudentInput
  submissions?: Prisma.AssessmentSubmissionCreateNestedManyWithoutStudentInput
}

export type StudentUncheckedCreateWithoutUserInput = {
  id?: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  programmeId?: number | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedCreateNestedManyWithoutStudentInput
  submissions?: Prisma.AssessmentSubmissionUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentCreateOrConnectWithoutUserInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutUserInput, Prisma.StudentUncheckedCreateWithoutUserInput>
}

export type StudentUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.StudentUpdateWithoutUserInput, Prisma.StudentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutUserInput, Prisma.StudentUncheckedCreateWithoutUserInput>
  where?: Prisma.StudentWhereInput
}

export type StudentUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.StudentWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutUserInput, Prisma.StudentUncheckedUpdateWithoutUserInput>
}

export type StudentUpdateWithoutUserInput = {
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  programme?: Prisma.ProgrammeUpdateOneWithoutStudentsNestedInput
  enrollments?: Prisma.StudentEnrollmentUpdateManyWithoutStudentNestedInput
  submissions?: Prisma.AssessmentSubmissionUpdateManyWithoutStudentNestedInput
}

export type StudentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  programmeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedUpdateManyWithoutStudentNestedInput
  submissions?: Prisma.AssessmentSubmissionUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentCreateWithoutProgrammeInput = {
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutStudentInput
  enrollments?: Prisma.StudentEnrollmentCreateNestedManyWithoutStudentInput
  submissions?: Prisma.AssessmentSubmissionCreateNestedManyWithoutStudentInput
}

export type StudentUncheckedCreateWithoutProgrammeInput = {
  id?: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  userId?: number | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedCreateNestedManyWithoutStudentInput
  submissions?: Prisma.AssessmentSubmissionUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentCreateOrConnectWithoutProgrammeInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutProgrammeInput, Prisma.StudentUncheckedCreateWithoutProgrammeInput>
}

export type StudentCreateManyProgrammeInputEnvelope = {
  data: Prisma.StudentCreateManyProgrammeInput | Prisma.StudentCreateManyProgrammeInput[]
  skipDuplicates?: boolean
}

export type StudentUpsertWithWhereUniqueWithoutProgrammeInput = {
  where: Prisma.StudentWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentUpdateWithoutProgrammeInput, Prisma.StudentUncheckedUpdateWithoutProgrammeInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutProgrammeInput, Prisma.StudentUncheckedCreateWithoutProgrammeInput>
}

export type StudentUpdateWithWhereUniqueWithoutProgrammeInput = {
  where: Prisma.StudentWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutProgrammeInput, Prisma.StudentUncheckedUpdateWithoutProgrammeInput>
}

export type StudentUpdateManyWithWhereWithoutProgrammeInput = {
  where: Prisma.StudentScalarWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyWithoutProgrammeInput>
}

export type StudentScalarWhereInput = {
  AND?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
  OR?: Prisma.StudentScalarWhereInput[]
  NOT?: Prisma.StudentScalarWhereInput | Prisma.StudentScalarWhereInput[]
  id?: Prisma.IntFilter<"Student"> | number
  studentUid?: Prisma.StringFilter<"Student"> | string
  fullName?: Prisma.StringFilter<"Student"> | string
  email?: Prisma.StringFilter<"Student"> | string
  dateOfBirth?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  academicYear?: Prisma.IntNullableFilter<"Student"> | number | null
  status?: Prisma.IntFilter<"Student"> | number
  hasOverdueBalance?: Prisma.BoolFilter<"Student"> | boolean
  userId?: Prisma.IntNullableFilter<"Student"> | number | null
  programmeId?: Prisma.IntNullableFilter<"Student"> | number | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Student"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Student"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Student"> | Date | string
}

export type StudentCreateWithoutEnrollmentsInput = {
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutStudentInput
  programme?: Prisma.ProgrammeCreateNestedOneWithoutStudentsInput
  submissions?: Prisma.AssessmentSubmissionCreateNestedManyWithoutStudentInput
}

export type StudentUncheckedCreateWithoutEnrollmentsInput = {
  id?: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  userId?: number | null
  programmeId?: number | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentCreateOrConnectWithoutEnrollmentsInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutEnrollmentsInput, Prisma.StudentUncheckedCreateWithoutEnrollmentsInput>
}

export type StudentUpsertWithoutEnrollmentsInput = {
  update: Prisma.XOR<Prisma.StudentUpdateWithoutEnrollmentsInput, Prisma.StudentUncheckedUpdateWithoutEnrollmentsInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutEnrollmentsInput, Prisma.StudentUncheckedCreateWithoutEnrollmentsInput>
  where?: Prisma.StudentWhereInput
}

export type StudentUpdateToOneWithWhereWithoutEnrollmentsInput = {
  where?: Prisma.StudentWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutEnrollmentsInput, Prisma.StudentUncheckedUpdateWithoutEnrollmentsInput>
}

export type StudentUpdateWithoutEnrollmentsInput = {
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutStudentNestedInput
  programme?: Prisma.ProgrammeUpdateOneWithoutStudentsNestedInput
  submissions?: Prisma.AssessmentSubmissionUpdateManyWithoutStudentNestedInput
}

export type StudentUncheckedUpdateWithoutEnrollmentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  programmeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submissions?: Prisma.AssessmentSubmissionUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentCreateWithoutSubmissionsInput = {
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutStudentInput
  programme?: Prisma.ProgrammeCreateNestedOneWithoutStudentsInput
  enrollments?: Prisma.StudentEnrollmentCreateNestedManyWithoutStudentInput
}

export type StudentUncheckedCreateWithoutSubmissionsInput = {
  id?: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  userId?: number | null
  programmeId?: number | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentCreateOrConnectWithoutSubmissionsInput = {
  where: Prisma.StudentWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentCreateWithoutSubmissionsInput, Prisma.StudentUncheckedCreateWithoutSubmissionsInput>
}

export type StudentUpsertWithoutSubmissionsInput = {
  update: Prisma.XOR<Prisma.StudentUpdateWithoutSubmissionsInput, Prisma.StudentUncheckedUpdateWithoutSubmissionsInput>
  create: Prisma.XOR<Prisma.StudentCreateWithoutSubmissionsInput, Prisma.StudentUncheckedCreateWithoutSubmissionsInput>
  where?: Prisma.StudentWhereInput
}

export type StudentUpdateToOneWithWhereWithoutSubmissionsInput = {
  where?: Prisma.StudentWhereInput
  data: Prisma.XOR<Prisma.StudentUpdateWithoutSubmissionsInput, Prisma.StudentUncheckedUpdateWithoutSubmissionsInput>
}

export type StudentUpdateWithoutSubmissionsInput = {
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutStudentNestedInput
  programme?: Prisma.ProgrammeUpdateOneWithoutStudentsNestedInput
  enrollments?: Prisma.StudentEnrollmentUpdateManyWithoutStudentNestedInput
}

export type StudentUncheckedUpdateWithoutSubmissionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  programmeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentCreateManyProgrammeInput = {
  id?: number
  studentUid: string
  fullName: string
  email: string
  dateOfBirth?: Date | string | null
  academicYear?: number | null
  status?: number
  hasOverdueBalance?: boolean
  userId?: number | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StudentUpdateWithoutProgrammeInput = {
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutStudentNestedInput
  enrollments?: Prisma.StudentEnrollmentUpdateManyWithoutStudentNestedInput
  submissions?: Prisma.AssessmentSubmissionUpdateManyWithoutStudentNestedInput
}

export type StudentUncheckedUpdateWithoutProgrammeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.StudentEnrollmentUncheckedUpdateManyWithoutStudentNestedInput
  submissions?: Prisma.AssessmentSubmissionUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentUncheckedUpdateManyWithoutProgrammeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentUid?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  academicYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.IntFieldUpdateOperationsInput | number
  hasOverdueBalance?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type StudentCountOutputType
 */

export type StudentCountOutputType = {
  enrollments: number
  submissions: number
}

export type StudentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  enrollments?: boolean | StudentCountOutputTypeCountEnrollmentsArgs
  submissions?: boolean | StudentCountOutputTypeCountSubmissionsArgs
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentCountOutputType
   */
  select?: Prisma.StudentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeCountEnrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentEnrollmentWhereInput
}

/**
 * StudentCountOutputType without action
 */
export type StudentCountOutputTypeCountSubmissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentSubmissionWhereInput
}


export type StudentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentUid?: boolean
  fullName?: boolean
  email?: boolean
  dateOfBirth?: boolean
  academicYear?: boolean
  status?: boolean
  hasOverdueBalance?: boolean
  userId?: boolean
  programmeId?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Student$userArgs<ExtArgs>
  programme?: boolean | Prisma.Student$programmeArgs<ExtArgs>
  enrollments?: boolean | Prisma.Student$enrollmentsArgs<ExtArgs>
  submissions?: boolean | Prisma.Student$submissionsArgs<ExtArgs>
  _count?: boolean | Prisma.StudentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["student"]>

export type StudentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentUid?: boolean
  fullName?: boolean
  email?: boolean
  dateOfBirth?: boolean
  academicYear?: boolean
  status?: boolean
  hasOverdueBalance?: boolean
  userId?: boolean
  programmeId?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Student$userArgs<ExtArgs>
  programme?: boolean | Prisma.Student$programmeArgs<ExtArgs>
}, ExtArgs["result"]["student"]>

export type StudentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentUid?: boolean
  fullName?: boolean
  email?: boolean
  dateOfBirth?: boolean
  academicYear?: boolean
  status?: boolean
  hasOverdueBalance?: boolean
  userId?: boolean
  programmeId?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Student$userArgs<ExtArgs>
  programme?: boolean | Prisma.Student$programmeArgs<ExtArgs>
}, ExtArgs["result"]["student"]>

export type StudentSelectScalar = {
  id?: boolean
  studentUid?: boolean
  fullName?: boolean
  email?: boolean
  dateOfBirth?: boolean
  academicYear?: boolean
  status?: boolean
  hasOverdueBalance?: boolean
  userId?: boolean
  programmeId?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StudentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "studentUid" | "fullName" | "email" | "dateOfBirth" | "academicYear" | "status" | "hasOverdueBalance" | "userId" | "programmeId" | "deletedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["student"]>
export type StudentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Student$userArgs<ExtArgs>
  programme?: boolean | Prisma.Student$programmeArgs<ExtArgs>
  enrollments?: boolean | Prisma.Student$enrollmentsArgs<ExtArgs>
  submissions?: boolean | Prisma.Student$submissionsArgs<ExtArgs>
  _count?: boolean | Prisma.StudentCountOutputTypeDefaultArgs<ExtArgs>
}
export type StudentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Student$userArgs<ExtArgs>
  programme?: boolean | Prisma.Student$programmeArgs<ExtArgs>
}
export type StudentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Student$userArgs<ExtArgs>
  programme?: boolean | Prisma.Student$programmeArgs<ExtArgs>
}

export type $StudentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Student"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
    programme: Prisma.$ProgrammePayload<ExtArgs> | null
    enrollments: Prisma.$StudentEnrollmentPayload<ExtArgs>[]
    submissions: Prisma.$AssessmentSubmissionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    studentUid: string
    fullName: string
    email: string
    dateOfBirth: Date | null
    academicYear: number | null
    status: number
    hasOverdueBalance: boolean
    userId: number | null
    programmeId: number | null
    deletedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["student"]>
  composites: {}
}

export type StudentGetPayload<S extends boolean | null | undefined | StudentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StudentPayload, S>

export type StudentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StudentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StudentCountAggregateInputType | true
  }

export interface StudentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Student'], meta: { name: 'Student' } }
  /**
   * Find zero or one Student that matches the filter.
   * @param {StudentFindUniqueArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StudentFindUniqueArgs>(args: Prisma.SelectSubset<T, StudentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Student that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StudentFindUniqueOrThrowArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StudentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StudentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Student that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentFindFirstArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StudentFindFirstArgs>(args?: Prisma.SelectSubset<T, StudentFindFirstArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Student that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentFindFirstOrThrowArgs} args - Arguments to find a Student
   * @example
   * // Get one Student
   * const student = await prisma.student.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StudentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StudentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Students that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Students
   * const students = await prisma.student.findMany()
   * 
   * // Get first 10 Students
   * const students = await prisma.student.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const studentWithIdOnly = await prisma.student.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StudentFindManyArgs>(args?: Prisma.SelectSubset<T, StudentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Student.
   * @param {StudentCreateArgs} args - Arguments to create a Student.
   * @example
   * // Create one Student
   * const Student = await prisma.student.create({
   *   data: {
   *     // ... data to create a Student
   *   }
   * })
   * 
   */
  create<T extends StudentCreateArgs>(args: Prisma.SelectSubset<T, StudentCreateArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Students.
   * @param {StudentCreateManyArgs} args - Arguments to create many Students.
   * @example
   * // Create many Students
   * const student = await prisma.student.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StudentCreateManyArgs>(args?: Prisma.SelectSubset<T, StudentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Students and returns the data saved in the database.
   * @param {StudentCreateManyAndReturnArgs} args - Arguments to create many Students.
   * @example
   * // Create many Students
   * const student = await prisma.student.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Students and only return the `id`
   * const studentWithIdOnly = await prisma.student.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StudentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StudentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Student.
   * @param {StudentDeleteArgs} args - Arguments to delete one Student.
   * @example
   * // Delete one Student
   * const Student = await prisma.student.delete({
   *   where: {
   *     // ... filter to delete one Student
   *   }
   * })
   * 
   */
  delete<T extends StudentDeleteArgs>(args: Prisma.SelectSubset<T, StudentDeleteArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Student.
   * @param {StudentUpdateArgs} args - Arguments to update one Student.
   * @example
   * // Update one Student
   * const student = await prisma.student.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StudentUpdateArgs>(args: Prisma.SelectSubset<T, StudentUpdateArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Students.
   * @param {StudentDeleteManyArgs} args - Arguments to filter Students to delete.
   * @example
   * // Delete a few Students
   * const { count } = await prisma.student.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StudentDeleteManyArgs>(args?: Prisma.SelectSubset<T, StudentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Students.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Students
   * const student = await prisma.student.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StudentUpdateManyArgs>(args: Prisma.SelectSubset<T, StudentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Students and returns the data updated in the database.
   * @param {StudentUpdateManyAndReturnArgs} args - Arguments to update many Students.
   * @example
   * // Update many Students
   * const student = await prisma.student.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Students and only return the `id`
   * const studentWithIdOnly = await prisma.student.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StudentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StudentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Student.
   * @param {StudentUpsertArgs} args - Arguments to update or create a Student.
   * @example
   * // Update or create a Student
   * const student = await prisma.student.upsert({
   *   create: {
   *     // ... data to create a Student
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Student we want to update
   *   }
   * })
   */
  upsert<T extends StudentUpsertArgs>(args: Prisma.SelectSubset<T, StudentUpsertArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Students.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentCountArgs} args - Arguments to filter Students to count.
   * @example
   * // Count the number of Students
   * const count = await prisma.student.count({
   *   where: {
   *     // ... the filter for the Students we want to count
   *   }
   * })
  **/
  count<T extends StudentCountArgs>(
    args?: Prisma.Subset<T, StudentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StudentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Student.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StudentAggregateArgs>(args: Prisma.Subset<T, StudentAggregateArgs>): Prisma.PrismaPromise<GetStudentAggregateType<T>>

  /**
   * Group by Student.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StudentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StudentGroupByArgs['orderBy'] }
      : { orderBy?: StudentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StudentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Student model
 */
readonly fields: StudentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Student.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StudentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.Student$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  programme<T extends Prisma.Student$programmeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$programmeArgs<ExtArgs>>): Prisma.Prisma__ProgrammeClient<runtime.Types.Result.GetResult<Prisma.$ProgrammePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  enrollments<T extends Prisma.Student$enrollmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$enrollmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentEnrollmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  submissions<T extends Prisma.Student$submissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Student$submissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentSubmissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Student model
 */
export interface StudentFieldRefs {
  readonly id: Prisma.FieldRef<"Student", 'Int'>
  readonly studentUid: Prisma.FieldRef<"Student", 'String'>
  readonly fullName: Prisma.FieldRef<"Student", 'String'>
  readonly email: Prisma.FieldRef<"Student", 'String'>
  readonly dateOfBirth: Prisma.FieldRef<"Student", 'DateTime'>
  readonly academicYear: Prisma.FieldRef<"Student", 'Int'>
  readonly status: Prisma.FieldRef<"Student", 'Int'>
  readonly hasOverdueBalance: Prisma.FieldRef<"Student", 'Boolean'>
  readonly userId: Prisma.FieldRef<"Student", 'Int'>
  readonly programmeId: Prisma.FieldRef<"Student", 'Int'>
  readonly deletedAt: Prisma.FieldRef<"Student", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Student", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Student", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Student findUnique
 */
export type StudentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student findUniqueOrThrow
 */
export type StudentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student findFirst
 */
export type StudentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Students.
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Students.
   */
  distinct?: Prisma.StudentScalarFieldEnum | Prisma.StudentScalarFieldEnum[]
}

/**
 * Student findFirstOrThrow
 */
export type StudentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Student to fetch.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Students.
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Students.
   */
  distinct?: Prisma.StudentScalarFieldEnum | Prisma.StudentScalarFieldEnum[]
}

/**
 * Student findMany
 */
export type StudentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter, which Students to fetch.
   */
  where?: Prisma.StudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Students to fetch.
   */
  orderBy?: Prisma.StudentOrderByWithRelationInput | Prisma.StudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Students.
   */
  cursor?: Prisma.StudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Students from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Students.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Students.
   */
  distinct?: Prisma.StudentScalarFieldEnum | Prisma.StudentScalarFieldEnum[]
}

/**
 * Student create
 */
export type StudentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * The data needed to create a Student.
   */
  data: Prisma.XOR<Prisma.StudentCreateInput, Prisma.StudentUncheckedCreateInput>
}

/**
 * Student createMany
 */
export type StudentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Students.
   */
  data: Prisma.StudentCreateManyInput | Prisma.StudentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Student createManyAndReturn
 */
export type StudentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * The data used to create many Students.
   */
  data: Prisma.StudentCreateManyInput | Prisma.StudentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Student update
 */
export type StudentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * The data needed to update a Student.
   */
  data: Prisma.XOR<Prisma.StudentUpdateInput, Prisma.StudentUncheckedUpdateInput>
  /**
   * Choose, which Student to update.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student updateMany
 */
export type StudentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Students.
   */
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyInput>
  /**
   * Filter which Students to update
   */
  where?: Prisma.StudentWhereInput
  /**
   * Limit how many Students to update.
   */
  limit?: number
}

/**
 * Student updateManyAndReturn
 */
export type StudentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * The data used to update Students.
   */
  data: Prisma.XOR<Prisma.StudentUpdateManyMutationInput, Prisma.StudentUncheckedUpdateManyInput>
  /**
   * Filter which Students to update
   */
  where?: Prisma.StudentWhereInput
  /**
   * Limit how many Students to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Student upsert
 */
export type StudentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * The filter to search for the Student to update in case it exists.
   */
  where: Prisma.StudentWhereUniqueInput
  /**
   * In case the Student found by the `where` argument doesn't exist, create a new Student with this data.
   */
  create: Prisma.XOR<Prisma.StudentCreateInput, Prisma.StudentUncheckedCreateInput>
  /**
   * In case the Student was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StudentUpdateInput, Prisma.StudentUncheckedUpdateInput>
}

/**
 * Student delete
 */
export type StudentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  /**
   * Filter which Student to delete.
   */
  where: Prisma.StudentWhereUniqueInput
}

/**
 * Student deleteMany
 */
export type StudentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Students to delete
   */
  where?: Prisma.StudentWhereInput
  /**
   * Limit how many Students to delete.
   */
  limit?: number
}

/**
 * Student.user
 */
export type Student$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Student.programme
 */
export type Student$programmeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Programme
   */
  select?: Prisma.ProgrammeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Programme
   */
  omit?: Prisma.ProgrammeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgrammeInclude<ExtArgs> | null
  where?: Prisma.ProgrammeWhereInput
}

/**
 * Student.enrollments
 */
export type Student$enrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentEnrollment
   */
  select?: Prisma.StudentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentEnrollment
   */
  omit?: Prisma.StudentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentEnrollmentInclude<ExtArgs> | null
  where?: Prisma.StudentEnrollmentWhereInput
  orderBy?: Prisma.StudentEnrollmentOrderByWithRelationInput | Prisma.StudentEnrollmentOrderByWithRelationInput[]
  cursor?: Prisma.StudentEnrollmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudentEnrollmentScalarFieldEnum | Prisma.StudentEnrollmentScalarFieldEnum[]
}

/**
 * Student.submissions
 */
export type Student$submissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentSubmission
   */
  select?: Prisma.AssessmentSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentSubmission
   */
  omit?: Prisma.AssessmentSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentSubmissionInclude<ExtArgs> | null
  where?: Prisma.AssessmentSubmissionWhereInput
  orderBy?: Prisma.AssessmentSubmissionOrderByWithRelationInput | Prisma.AssessmentSubmissionOrderByWithRelationInput[]
  cursor?: Prisma.AssessmentSubmissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssessmentSubmissionScalarFieldEnum | Prisma.AssessmentSubmissionScalarFieldEnum[]
}

/**
 * Student without action
 */
export type StudentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
}
