
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * Application user. `role` is persisted as an Int (0..3) and mapped at the
 * application layer via `lib/auth/roles.ts` so the schema stays free of enum
 * types. Values: 0=STUDENT, 1=STAFF, 2=REGISTRAR, 3=ADMIN.
 */
export type User = Prisma.UserModel
/**
 * Model Student
 * Registry record for a student. Authentication remains owned by User.
 * Student-facing identity is `studentUid`; retain the legacy User link while
 * registry routes still use it.
 */
export type Student = Prisma.StudentModel
/**
 * Model Programme
 * Catalogue data only. Enrolment and payment workflows are separate features.
 */
export type Programme = Prisma.ProgrammeModel
/**
 * Model StudentEnrollment
 * Financial snapshot for one student taking one programme in one academic year.
 * Snapshot fields are never changed when catalogue pricing or coupons change.
 */
export type StudentEnrollment = Prisma.StudentEnrollmentModel
/**
 * Model PaymentTransaction
 * Immutable internal payment ledger entry. No provider, refund, or void semantics are modeled yet.
 */
export type PaymentTransaction = Prisma.PaymentTransactionModel
/**
 * Model Assessment
 * Assessment ownership is programme-scoped. `subjectName` is intentionally
 * a scalar until the registry has a first-class module/course entity.
 */
export type Assessment = Prisma.AssessmentModel
/**
 * Model AssessmentSubmission
 * 
 */
export type AssessmentSubmission = Prisma.AssessmentSubmissionModel
/**
 * Model UserLog
 * 
 */
export type UserLog = Prisma.UserLogModel
