
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * Application user. `role` is persisted as an Int (0..3) and mapped at the
 * application layer via `lib/auth/roles.ts` so the schema stays free of enum
 * types. Values: 0=STUDENT, 1=STAFF, 2=REGISTRAR, 3=ADMIN.
 */
export type User = Prisma.UserModel
/**
 * Model Student
 * Registry record for a student. Authentication remains owned by User.
 * Student-facing identity is `studentUid`; retain the legacy User link while
 * registry routes still use it.
 */
export type Student = Prisma.StudentModel
/**
 * Model Programme
 * Catalogue data only. Enrolment and payment workflows are separate features.
 */
export type Programme = Prisma.ProgrammeModel
/**
 * Model StudentEnrollment
 * Financial snapshot for one student taking one programme in one academic year.
 * Snapshot fields are never changed when catalogue pricing or coupons change.
 */
export type StudentEnrollment = Prisma.StudentEnrollmentModel
/**
 * Model PaymentTransaction
 * Immutable internal payment ledger entry. No provider, refund, or void semantics are modeled yet.
 */
export type PaymentTransaction = Prisma.PaymentTransactionModel
/**
 * Model Assessment
 * Assessment ownership is programme-scoped. `subjectName` is intentionally
 * a scalar until the registry has a first-class module/course entity.
 */
export type Assessment = Prisma.AssessmentModel
/**
 * Model AssessmentSubmission
 * 
 */
export type AssessmentSubmission = Prisma.AssessmentSubmissionModel
/**
 * Model UserLog
 * 
 */
export type UserLog = Prisma.UserLogModel
