
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Student'
export type * from './models/Programme'
export type * from './models/StudentEnrollment'
export type * from './models/PaymentTransaction'
export type * from './models/Assessment'
export type * from './models/AssessmentSubmission'
export type * from './models/UserLog'
export type * from './commonInputTypes'