// Constants for `UserLog.eventType`. Stored as a plain string column in the
// database so schema migrations are not required to add new event types.
// Use these constants (not the strings) at every call site so the compiler
// catches typos.

export const LogEvent = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  PASSWORD_RESET: "PASSWORD_RESET",
  STUDENT_REGISTER: "STUDENT_REGISTER",
  OTP_SENT: "OTP_SENT",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_FAILED: "OTP_FAILED",
  STUDENT_LINK_FAILED: "STUDENT_LINK_FAILED",
  STUDENT_LINK_CREATED: "STUDENT_LINK_CREATED",
  STUDENT_LOGIN_SUCCESS: "STUDENT_LOGIN_SUCCESS",
  STUDENT_LOGIN_FAILURE: "STUDENT_LOGIN_FAILURE",
  ENROLLMENT_CREATED: "ENROLLMENT_CREATED",
  ENROLLMENT_STATUS_CHANGED: "ENROLLMENT_STATUS_CHANGED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  ASSESSMENT_CREATED: "ASSESSMENT_CREATED",
  ASSESSMENT_UPDATED: "ASSESSMENT_UPDATED",
  ASSESSMENT_PUBLISHED: "ASSESSMENT_PUBLISHED",
  SUBMISSION_CREATED: "SUBMISSION_CREATED",
  RESULT_GRADED: "RESULT_GRADED",
  RESULT_PUBLISHED: "RESULT_PUBLISHED",
  FILE_UPLOADED: "FILE_UPLOADED",
} as const;

export type LogEventValue = (typeof LogEvent)[keyof typeof LogEvent];
